var quests_list = [
"well-хорошо",
"only-только",
"those-тот",
"tell-говорить",
"one-third",
"very-очень",
"her-ее",
"even-даже",
"back-спина",
"any-Любые",
"good-хороший",
"woman-женщина",
"through-через",
"us-нас",
"life-жизнь",
"child-ребенок",
"there-там",
"work-работать",
"down-внизу",
"May-май",
"after-после",
"should-следует (от shall)",
"call-звонить",
"world-мир",
"over-через",
"school-школа",
"still-все еще",
"try-пробовать",
"in-в",
"as-как",
"last-прошлый",
"ask-просить",
"need-нуждаться в",
"too-слишком",
"feel-чувствовать",
"three-три",
"when-когда",
"state-государство",
"never-никогда",
"become-становиться",
"between-между",
"high-высокий (h-)",
"really-на самом деле",
"something-что",
"most-самый",
"another-еще один",
"much-много (с неисчисляемыми существительными)",
"family-семья",
"own-иметь",
"out-вне",
"leave-оставлять",
"put-класть",
"old-старый",
"while-пока",
"mean-означать",
"on-на",
"keep-(со)держать",
"student-студент",
"why-почему",
"let-позволять",
"great-великий",
"same-тот же",
"big-большой",
"group-группа",
"begin-начинать(ся)",
"seem-казаться",
"country-страна",
"help-помощь",
"talk-говорить",
"where-где",
"turn-поворачивать",
"problem-проблема",
"every-каждый",
"start-начинать",
"hand-рука",
"might-можно",
"American-американский",
"show-показывать",
"part-часть",
"about-о",
"against-против",
"place-место",
"such-такой",
"again-снова",
"few-мало",
"case-случай",
"week-неделя",
"company-компания",
"system-система",
"each-каждый",
"right-правильный",
"program-программа",
"hear-слышать",
"so-так",
"question-вопрос",
"during-во время",
"play-играть",
"government-правительство",
"run-бегать",
"small-маленький",
"number-номер",
"off-прочь",
"always-всегда",
"move-двигать(ся)",
"like-любить",
"night-ночь",
"live-жить",
"Mr-Мистер",
"point-точка",
"believe-верить",
"hold-держать(ся)",
"today-сегодня",
"bring-приносить",
"happen-случаться",
"next-следующий",
"without-без",
"before-перед",
"large-большой",
"all-все",
"million-миллион",
"must-должен",
"home-дом",
"under-под",
"water-вода",
"room-комната",
"write-писать",
"mother-мама",
"area-площадь",
"national-национальный",
"money-деньги",
"story-рассказ",
"young-молодой",
"fact-сущность",
"month-месяц",
"different-другой",
"lot-много",
"study-учиться",
"book-книга",
"eye-глаз",
"job-работа",
"word-слово",
"though-хотя",
"business-дело",
"issue-выпуск",
"side-сторона",
"kind-добрый",
"four-четыре",
"head-голова",
"far-далеко",
"black-черный",
"long-длинный",
"both-оба",
"little-мало",
"house-дом",
"yes-да",
"since-с тех пор как",
"provide-обеспечивать",
"service-сервис",
"around-вокруг",
"friend-друг",
"important-важный",
"father-папа",
"sit-сидеть",
"away-прочь",
"until-до",
"power-держава",
"hour-час",
"game-игра",
"often-часто",
"yet-однако",
"line-линия",
"political-политический",
"end-конец",
"among-среди (не midst)",
"ever-когда-либо !NEW!",
"stand-остановка",
"bad-плохой",
"lose-терять",
"however-однако",
"member-член",
"pay-платить",
"law-закон",
"meet-встречать(ся)",
"car-машина",
"city-город",
"almost-почти",
"include-включать",
"continue-продолжать(ся)",
"set-класть",
"later-позже",
"community-община",
"name-имя",
"five-пять",
"once-один раз",
"white-белый",
"least-наименьший",
"president-президент",
"learn-узнать",
"real-реальный",
"change-мелкие деньги",
"team-команда",
"minute-минута",
"best-наилучший",
"several-несколько",
"idea-идея",
"kid-ребенок (разг.)",
"body-тело",
"information-информация",
"nothing-ничто",
"ago-тому назад",
"lead-вести",
"social-общественный",
"understand-понимать",
"whether-ли",
"watch-часы",
"together-вместе",
"follow-следовать",
"parent-родитель",
"stop-остановка",
"face-лицо",
"anything-что",
"create-создавать",
"public-общественный (не social)",
"already-уже",
"speak-говорить",
"others-другие",
"read-читать",
"level-уровень",
"allow-разрешать",
"add-добавлять",
"office-офис",
"spend-тратить",
"door-дверь",
"health-здоровье",
"person-человек",
"art-искусство",
"sure-уверенный",
"war-война",
"history-история",
"party-вечеринка",
"within-внутри",
"grow-расти",
"result-результат",
"open-открывать",
"morning-утро",
"walk-гулять",
"reason-причина",
"low-низкий",
"win-выигрывать",
"research-исследование",
"girl-девочка",
"guy-парень g- !NEW!",
"early-рано",
"food-пища (не meal)",
"moment-момент",
"himself-себя",
"air-воздушный",
"teacher-учитель",
"force-сила",
"offer-предлагать",
"enough-достаточный",
"education-образование",
"across-через",
"although-хотя",
"remember-помнить",
"foot-нога",
"second-второй",
"boy-мальчик",
"maybe-мoжет быть",
"toward-к",
"able-способный (-e)",
"age-век",
"policy-политика",
"everything-все",
"love-любовь",
"process-процесс",
"music-музыка",
"including-включая",
"consider-считать",
"appear-появляться",
"actually-фактически",
"buy-покупать",
"probably-вероятно (-y)",
"human-человеческий",
"wait-ждать",
"serve-служить",
"market-рынок",
"die-штамповать",
"send-отправлять",
"expect-ожидать",
"sense-чувство",
"build-строить",
"stay-оставаться",
"fall-падать",
"oh-O!",
"nation-нация",
"plan-план",
"cut-разрез",
"college-колледж",
"interest-интересовать",
"death-смерть",
"course-курс",
"someone-кто то",
"experience-опыт",
"behind-позади",
"reach-достигать",
"local-местный",
"kill-убивать",
"six-шесть",
"remain-оставаться",
"effect-действие",
"use-использовать",
"yeah-да !NEW!",
"suggest-предлагать",
"class-класс (не grade)",
"control-контроль",
"raise-поднимать",
"care-заботиться",
"perhaps-возможно",
"late-поздно",
"hard-с трудом",
"field-поле",
"else-еще",
"pass-передавать",
"former-бывший",
"sell-продавать",
"major-специализироваться",
"sometimes-иногда",
"require-требовать",
"along-вдоль",
"development-развитие",
"themselves-себя",
"report-доклад",
"role-роль",
"better-лучше",
"economic-экономической",
"effort-усилие",
"up-вверх",
"decide-решать",
"rate-тариф",
"strong-сильный",
"possible-возможный",
"heart-сердце",
"drug-лекарство",
"leader-глава",
"light-свет",
"voice-голос",
"wife-жена",
"whole-целый",
"police-полиция",
"mind-память",
"finally-в конце концов",
"pull-тянуть",
"return-вернуть(ся)",
"free-свободный",
"military-военный",
"price-цена",
"less-менее",
"according-согласно -ing",
"decision-решение",
"explain-объяснять",
"son-сын",
"hope-надеяться",
"develop-развивать",
"view-взгляд",
"relationship-родственные связи",
"carry-нести",
"town-город (не city)",
"road-дорога",
"drive-водить машину",
"arm-рука",
"TRUE-ПРАВДА",
"federal-федеральный",
"break-ломать",
"difference-разница",
"thank-благодарить",
"receive-получать",
"value-ценность",
"international-международный",
"building-здание",
"action-действие",
"full-полный",
"model-модель",
"join-соединяться",
"season-время года",
"society-общество",
"because-потому что",
"tax-налог",
"director-режиссер",
"position-положение",
"player-плейер",
"agree-соглашаться",
"especially-особенно",
"record-запись",
"pick-собирать",
"wear-одежда",
"paper-бумага",
"special-специальный",
"space-пространство",
"ground-земля",
"form-бланк",
"support-поддерживать",
"event-событие",
"official-официальный",
"whose-чей",
"matter-дело",
"everyone-все",
"center-центр",
"couple-пара",
"site-местоположение",
"project-проект",
"hit-успех",
"base-основа",
"activity-деятельность",
"star-звезда",
"table-стол",
"court-корт",
"produce-производить",
"eat-есть (принимать пищу)",
"teach-обучать",
"oil-масло",
"half-половина",
"situation-положение",
"easy-легкий",
"cost-стоить",
"industry-промышленность",
"figure-фигура",
"street-улица",
"image-изображение",
"itself-себя",
"phone-телефон",
"either-или",
"data-данные",
"cover-покрывало",
"quite-вполне",
"picture-картина",
"clear-ясный",
"practice-практика",
"piece-кусок",
"land-земля",
"recent-недавний",
"describe-описывать",
"product-продукция",
"doctor-доктор",
"wall-стена",
"patient-пациент",
"worker-рабочий",
"news-новости",
"test-анализ",
"movie-кино",
"certain-определенный",
"north-север",
"personal-личный",
"simply-просто",
"third-третий",
"technology-технологии",
"catch-уловить",
"step-шаг",
"baby-ребенок",
"computer-компьютер",
"type-тип",
"attention-внимание",
"draw-рисовать",
"film-фотопленка",
"Republican-республиканец",
"tree-дерево (tree)",
"source-источник",
"red-красный",
"nearly-почти",
"organization-организация",
"choose-выбирать c-",
"cause-дело",
"hair-волосы",
"look-смотреть",
"century-столетие",
"evidence-доказательство e-",
"window-окно",
"difficult-трудный",
"listen-слушать",
"soon-скоро",
"culture-культура",
"billion-биллион",
"chance-случай",
"brother-брат",
"energy-энергия",
"period-период",
"summer-лето",
"realize-представлять себе",
"hundred-сто",
"available-доступный",
"plant-завод",
"likely-вероятно",
"opportunity-возможность",
"term-семестр",
"short-короткий",
"letter-письмо",
"condition-условие",
"choice-выбор (c-",
"single-один",
"rule-правило",
"daughter-дочь",
"administration-администрация",
"south-юг",
"husband-муж",
"Congress-конгресс",
"floor-пол",
"campaign-компания",
"material-материал",
"population-население",
"economy-экономика",
"medical-медицинский",
"hospital-больница",
"church-церковь",
"close-закрывать(ся)",
"thousand-тысяча",
"risk-риск",
"current-течение",
"fire-огонь",
"future-будущее",
"wrong-неправильный",
"involve-втягивать",
"defense-оборона !NEW!",
"anyone-любой",
"increase-рост",
"security-безопасность",
"bank-банк",
"myself-себя",
"certainly-конечно",
"west-запад",
"sport-спорт",
"board-садиться на пароход",
"seek-искать (не find)",
"per-в",
"subject-предмет",
"officer-служащий",
"private-частный",
"rest-остальное",
"behavior-поведение",
"deal-значительное количество",
"performance-спектакль",
"fight-бороться",
"throw-бросать",
"top-верх",
"quickly-быстро",
"past-после",
"goal-цель",
"bed-постель",
"order-порядок",
"author-автор",
"fill-заполнить",
"represent-изображать",
"focus-фокусировать",
"foreign-иностранный",
"drop-капля",
"blood-кровь",
"upon-на",
"agency-агентство",
"push-толкать",
"nature-природа",
"color-Цвет ",
"no-нет",
"recently-недавно",
"store-магазин",
"reduce-уменьшать",
"sound-звук",
"note-запись",
"fine-прекрасно",
"near-близко от",
"movement-движение",
"page-страница",
"enter-входить",
"share-разделять",
"than-чем",
"common-общий",
"poor-бедный",
"other-другой",
"natural-естественный",
"race-раса",
"concern-забота c-",
"series-серия",
"significant-значительный s-",
"similar-похожий",
"hot-горячий",
"language-язык",
"usually-обычно",
"response-реакция",
"dead-мертвый",
"rise-подниматься",
"animal-животное",
"factor-фактор",
"decade-десятилетие",
"article-статья",
"shoot-стрелять",
"east-восток",
"save-спасать",
"seven-семь",
"artist-художник",
"scene-действие",
"stock-запас",
"career-профессия",
"despite-несмотря на",
"central-центральный",
"eight-восемь",
"thus-так",
"treatment-обращение",
"beyond-далеко",
"happy-счастливый",
"exactly-точно",
"protect-защищать",
"approach-приближаться",
"lie-ложь",
"size-размер",
"dog-собака",
"fund-фонд",
"serious-серьезный",
"occur-случаться",
"media-СМИ",
"ready-готовый",
"sign-подписывать(ся)",
"thought-думал",
"list-список",
"individual-личность",
"simple-простой",
"quality-качество",
"pressure-давление",
"accept-принимать",
"answer-ответ",
"resource-ресурс",
"identify-опознавать",
"left-покинутый",
"meeting-встреча",
"determine-определять",
"prepare-готовить(ся)",
"disease-болезнь *i-",
"whatever-что бы ни",
"success-успех",
"argue-спорить",
"cup-чашка",
"particularly-особенно",
"amount-количество",
"ability-способность (-y не от слова capable)",
"staff-штат",
"recognize-узнавать",
"indicate-показывать",
"character-характер",
"growth-рост",
"loss-потеря",
"degree-степень",
"wonder-удивляться",
"attack-нападение",
"herself-себя",
"region-район",
"television-телевидение",
"box-ящик",
"TV-телевизор",
"training-тренировка",
"pretty-хороший",
"trade-торговать",
"election-избрание",
"everybody-каждый",
"physical-физический",
"lay-класть",
"general-общий",
"feeling-чувство",
"standard-стандарт",
"bill-счет",
"message-сообщение",
"fail-недоставать",
"outside-снаружи",
"arrive-приезжать",
"analysis-анализ",
"benefit-благо",
"sex-пол",
"forward-передовой",
"lawyer-адвокат",
"present-настоящее время",
"section-отделение",
"environmental-экологическая",
"glass-стакан",
"skill-мастерство",
"sister-сестра",
"PM-ВЕЧЕРА",
"professor-профессор",
"operation-действие",
"financial-финансовый",
"crime-преступление",
"stage-сцена",
"ok-ОК",
"compare-сравнивать",
"authority-власть",
"miss-промах",
"design-проектировать",
"sort-сорт",
"act-акт",
"ten-десять",
"knowledge-знание",
"gun-ружье",
"station-станция",
"blue-синий",
"strategy-стратегия",
"clearly-ясно (не obvious)",
"discuss-обсуждать",
"indeed-неужели",
"truth-правда",
"song-песня",
"example-пример",
"democratic-демократической",
"check-проверять",
"environment-окружающая среда",
"leg-нога",
"dark-темный",
"various-различный",
"rather-скорее",
"laugh-смех",
"guess-отгадывать",
"executive-должностное лицо",
"prove-доказывать",
"hang-повесить",
"entire-полный",
"rock-скала",
"forget-забыть",
"claim-требовать",
"remove-удалять",
"manager-управляющий",
"enjoy-любить",
"network-сеть",
"legal-законный",
"religious-религиозный",
"cold-холод",
"final-окончательный",
"main-главный",
"science-наука",
"green-зеленый",
"memory-память",
"card-карточка",
"above-над",
"seat-место",
"cell-камера",
"establish-учреждать",
"nice-хороший",
"trial-попытка",
"expert-эксперт",
"that-это",
"spring-весна",
"firm-фирма",
"Democrat-демократ",
"radio-радио",
"visit-визит",
"management-управление",
"avoid-избегать",
"imagine-думать",
"tonight-сегодня вечером",
"huge-огромный (не bulk)",
"ball-мяч",
"finish-кончать(ся)",
"yourself-сам",
"theory-теория",
"impact-удар (не stroke)",
"respond-отвечать",
"statement-утверждение",
"maintain-поддерживать",
"charge-плата",
"popular-популярный",
"traditional-традиционный",
"onto-на (не upon)",
"reveal-обнаруживать r-",
"direction-направление",
"weapon-оружие",
"employee-служащий",
"cultural-культурный",
"contain-содержать",
"peace-мир",
"pain-боль",
"apply-обращаться",
"measure-мера",
"wide-широкий",
"shake-пожать (руки)",
"fly-летать",
"interview-встреча",
"manage-справляться",
"chair-стул",
"fish-рыба",
"particular-особый",
"camera-фотоаппарат",
"structure-структура",
"politics-политика",
"perform-делать",
"bit-кусочек",
"weight-вес",
"suddenly-внезапно",
"discover-открывать",
"candidate-кандидат",
"production-производство",
"treat-удовольствие",
"trip-поездка",
"evening-вечер",
"affect-влиять",
"inside-внутрь",
"conference-конференция",
"unit-единица",
"style-стиль",
"adult-взрослый",
"worry-беспокоиться",
"range-ряд",
"mention-благодарность",
"deep-глубокий",
"edge-край",
"specific-специфический",
"writer-писатель",
"trouble-неприятность",
"necessary-нужный",
"throughout-повсюду",
"challenge-вызывать",
"fear-страх",
"shoulder-плечо",
"institution-учреждение",
"middle-средний",
"sea-море",
"dream-мечтать",
"bar-бар",
"beautiful-красивый",
"property-собственность",
"instead-вместо",
"improve-улучшать",
"stuff-вещество",
"detail-деталь",
"method-метод",
"somebody-кто",
"magazine-журнал",
"hotel-гостиница",
"soldier-солдат",
"reflect-отражать",
"heavy-тяжелый",
"sexual-сексуальный",
"bag-сумка",
"heat-жара",
"marriage-свадьба",
"tough-жесткий",
"sing-пение",
"surface-поверхность",
"purpose-цель",
"exist-существовать",
"pattern-модель",
"whom-кому",
"skin-кожа",
"agent-деятель",
"owner-владелец",
"machine-машина",
"gas-газ",
"ahead-вперед",
"generation-поколение",
"commercial-торговый",
"address-адрес",
"cancer-рак",
"item-вещь",
"reality-действительность",
"coach-тренировать",
"Mrs-Г",
"yard-ярд",
"beat-ударить",
"violence-сила",
"total-сумма",
"tend-иметь тенденцию",
"investment-инвестиции",
"discussion-беседа",
"finger-палец",
"garden-сад",
"notice-извещение",
"collection-коллекция",
"modern-современный",
"task-задача",
"partner-участник",
"positive-положительный",
"civil-гражданский (-l)",
"kitchen-кухня",
"consumer-потребитель",
"shot-попытка",
"budget-бюджет",
"wish-желание",
"painting-живопись",
"scientist-ученый",
"safe-сейф",
"agreement-согласие",
"capital-столица",
"mouth-рот",
"nor-и не",
"victim-жертва",
"newspaper-газета",
"threat-угроза",
"responsibility-ответственность",
"smile-улыбаться",
"attorney-адвокат",
"score-счет",
"account-счет",
"interesting-интересный",
"audience-публика",
"rich-богатый",
"dinner-обед",
"vote-голос (на выборах)",
"western-западный",
"relate-относиться",
"travel-путешествовать",
"debate-дебаты",
"prevent-предотвращать",
"citizen-гражданин",
"majority-большинство",
"none-нисколько",
"front-перед",
"born-рожденный",
"admit-допускать",
"senior-старший s-",
"assume-принимать на себя",
"wind-ветер",
"key-ключ",
"professional-профессиональный",
"mission-миссия",
"fast-спешащий",
"alone-один",
"customer-клиент",
"suffer-страдать",
"speech-речь",
"successful-удачный",
"option-выбор (o-)",
"participant-участник",
"southern-южный",
"fresh-свежий",
"eventually-в конечном счете",
"forest-лес",
"video-видео",
"global-Глобальный",
"Senate-сенат",
"reform-улучшать",
"access-доступ",
"restaurant-ресторан",
"judge-судья",
"publish-публиковать",
"relation-отношение",
"release-освобождение",
"bird-птица",
"opinion-мнение",
"credit-кредит",
"critical-критический",
"corner-угол",
"concerned-заинтересованный",
"recall-припомнить",
"version-версия",
"stare-пристальный взгляд",
"safety-безопасность",
"effective-действующий",
"neighborhood-окрестности",
"original-оригинал",
"troop-войска",
"income-доход",
"directly-прямо",
"hurt-рана",
"species-порода",
"immediately-немедленно",
"track-след",
"basic-основной b-",
"strike-ударять",
"sky-небо",
"freedom-свобода f-",
"absolutely-абсолютно",
"plane-самолет",
"nobody-никто",
"achieve-достигать",
"object-возражать",
"attitude-позиция",
"labor-Рабочая сила ",
"refer-отсылать",
"concept-концепция",
"client-клиент",
"powerful-могущественный",
"perfect-совершенный",
"nine-девять",
"therefore-поэтому",
"conduct-вести",
"announce-объявлять",
"conversation-разговор",
"examine-рассматривать",
"touch-соприкосновение",
"please-пожалуйста (только в просьбе)",
"attend-посещать",
"completely-совершенно",
"variety-разнообразие",
"sleep-спать",
"involved-сложный",
"investigation-исследование",
"nuclear-ядерной",
"researcher-Исследователь",
"press-(по)гладить",
"conflict-конфликт",
"spirit-дух",
"replace-заменять",
"British-британский",
"encourage-ободрять",
"argument-спор",
"by-по",
"camp-лагерь",
"brain-мозг",
"feature-особенность",
"afternoon-время после полудня",
"AM-AM",
"weekend-выходные",
"dozen-дюжина",
"possibility-возможность p-",
"insurance-страхование",
"department-отдел",
"battle-бой",
"beginning-начало",
"date-дата",
"generally-вообще",
"African-American",
"sorry-сожалеющий",
"crisis-кризис",
"complete-полный",
"fan-болельщик",
"stick-палка",
"define-определять",
"easily-легко",
"hole-отверстие",
"element-элемент",
"vision-зрение",
"status-статус",
"normal-нормальный",
"Chinese-Китайский",
"ship-корабль",
"solution-решение",
"stone-камень",
"slowly-медленно",
"scale-масштаб",
"university-Университет",
"introduce-предстaвлять",
"driver-водитель",
"attempt-пробовать",
"park-парк",
"spot-пятно",
"lack-недостаток",
"ice-лед",
"boat-лодка",
"drink-напиток",
"sun-солнце",
"distance-расстояние",
"wood-лес",
"handle-обращаться с",
"truck-грузовик t-",
"mountain-гора",
"survey-осмотр",
"supposed-предполагаемый (от suppose)",
"tradition-традиция",
"winter-зима",
"village-деревня",
"Soviet-советский",
"refuse-отказывать",
"sales-продажи",
"roll-вращение",
"communication-сообщение",
"screen-экран",
"gain-прибыль",
"resident-постоянный житель",
"hide-прятать",
"gold-золото",
"club-клуб",
"farm-ферма",
"potential-потенциал",
"European-европейский",
"presence-присутствие",
"independent-независимый",
"district-район",
"shape-форма",
"reader-читатель",
"Ms-Миз",
"contract-договор",
"crowd-толпа",
"Christian-христианский",
"express-экспресс",
"apartment-квартира",
"willing-готовый",
"strength-численность",
"previous-предшествующий",
"band-лента",
"obviously-очевидно o-",
"horse-лошадь",
"interested-заинтересованный",
"target-задание",
"prison-тюрьма",
"ride-езда",
"guard-охрана",
"terms-личные отношения",
"demand-требовать",
"reporter-репортер",
"deliver-доставлять",
"text-текст",
"tool-инструмент",
"wild-исступленный",
"vehicle-транспортное средство",
"observe-наблюдать",
"flight-полет",
"facility-легкость",
"understanding-понимание",
"average-средний",
"emerge-появляться",
"advantage-преимущество",
"quick-быстрый",
"leadership-руководство",
"earn-зарабатывать",
"pound-фунт",
"basis-основа",
"bright-ясный",
"operate-действовать",
"guest-гость",
"sample-образец",
"contribute-делать вклад",
"tiny-крошечный",
"block-блок",
"protection-защита",
"settle-поселять",
"feed-кормить",
"collect-коллекционировать",
"additional-дополнительный",
"highly-очень",
"identity-идентичность",
"title-заглавие",
"mostly-главным образом (не mainly)",
"lesson-урок",
"faith-вера",
"river-река",
"promote-содействовать",
"living-средства к существованию",
"count-считать",
"unless-если не",
"marry-жениться",
"tomorrow-завтра",
"technique-техника",
"path-тропинка",
"ear-ухо",
"shop-магазин",
"folk-народная",
"principle-принцип",
"survive-пережить",
"lift-поднимать",
"border-граница",
"competition-соревнование",
"jump-прыгать",
"gather-собираться",
"limit-предел",
"fit-подходить",
"cry-кричать",
"equipment-снаряжение",
"worth-стоящий",
"associate-соединять",
"critic-критик",
"warm-теплый",
"aspect-взгляд",
"insist-настаивать",
"failure-неудача",
"annual-годовой",
"French-французский",
"Christmas-Рождество",
"comment-комментарий",
"responsible-ответственный",
"affair-дело",
"procedure-процедура",
"regular-регулярный",
"spread-распространяться",
"chairman-председатель",
"baseball-бейсбол",
"soft-мягкий",
"ignore-игнорировать",
"egg-яйцо",
"belief-вера",
"demonstrate-демонстрировать",
"anybody-кто",
"murder-убийство",
"gift-подарок",
"religion-религия",
"review-обзор",
"editor-редактор",
"engage-нанимать",
"coffee-кофе",
"document-документ",
"speed-скорость",
"cross-пересекать",
"influence-влияние",
"anyway-во что бы то ни стало",
"threaten-грозить",
"commit-совершать (преступление)",
"female-женщина",
"youth-молодежь",
"wave-волна",
"afraid-испуганный",
"quarter-четверть",
"background-фон",
"native-родной",
"broad-широкий",
"wonderful-замечательный",
"deny-отрицать",
"apparently-явно",
"slightly-слегка",
"reaction-реакция",
"twice-дважды",
"suit-костюм",
"perspective-перспектива",
"growing-растущий",
"blow-дуть",
"construction-строительство",
"intelligence-интеллект",
"destroy-разрушать",
"cook-готовить",
"connection-соединение",
"burn-гореть",
"shoe-ботинок",
"grade-сортировать",
"context-контекст",
"committee-комитет",
"hey-эй !NEW!",
"mistake-ошибка",
"location-местоположение",
"clothes-одежда",
"Indian-индийский",
"quiet-тихий",
"dress-платье",
"promise-обещать",
"aware-сознающий",
"neighbor-сосед",
"function-функция",
"bone-кость",
"active-активный",
"extend-продлевать",
"chief-шеф",
"combine-объединять (не connect)",
"wine-вино",
"below-ниже",
"cool-прохладный",
"voter-избиратель",
"learning-учение",
"bus-автобус",
"hell-черт",
"dangerous-опасный",
"remind-напоминать",
"moral-нравственный",
"United-объединенный",
"category-категория",
"relatively-относительно",
"victory-победа",
"academic-академический",
"Internet-интернет",
"healthy-здоровый",
"negative-отрицательный",
"following-следующий -ing",
"historical-исторический",
"medicine-медицина",
"tour-путешествие",
"depend-зависеть",
"photo-фотография",
"finding-находка",
"grab-внезапно схватывать",
"direct-прямой",
"classroom-класс",
"contact-устанавливать связь",
"justice-справедливость",
"participate-участвовать",
"daily-ежедневно",
"fair-любезно",
"pair-пара",
"famous-известный",
"exercise-упражнение",
"knee-колено",
"flower-цветок",
"tape-лента",
"hire-взять напрокат",
"familiar-близкий (f-)",
"appropriate-подходящий",
"supply-снабжать",
"fully-вполне",
"will-вспомогательный глагол будущего времени",
"actor-актер",
"birth-рождение",
"search-искать",
"tie-связь",
"democracy-демократия",
"eastern-восточный",
"primary-первичный",
"yesterday-вчера",
"circle-амфитеатр",
"device-прибор",
"progress-прогресс",
"bottom-дно",
"island-остров",
"exchange-обмен",
"clean-чистить",
"studio-студия",
"train-поезд",
"lady-дама",
"colleague-коллега",
"application-заявление",
"neck-шея",
"lean-прислоняться",
"damage-повреждать",
"plastic-пластмасса",
"tall-невероятный",
"plate-тарелка",
"hate-ненавидеть",
"otherwise-иначе",
"writing-письменность (-ing)",
"male-мужчина",
"alive-живой",
"expression-выразительность",
"football-футбол",
"intend-намереваться",
"chicken-цыпленок",
"army-армия",
"abuse-злоупотребление",
"theater-театр",
"shut-закрывать",
"map-карта",
"extra-сверх (не above)",
"session-заседание (не sitting)",
"danger-опасность",
"welcome-желанный",
"domestic-домашний",
"lots-уйма",
"literature-литература",
"rain-дождь",
"desire-желание",
"assessment-оценка",
"injury-телесное повреждение",
"respect-уважение",
"northern-северный",
"nod-кивать головой",
"paint-красить",
"fuel-топливо",
"leaf-лист",
"dry-сухой",
"Russian-русский",
"instruction-инструкция",
"pool-пруд",
"climb-подниматься",
"sweet-милый",
"engine-двигатель",
"fourth-четвертый",
"salt-соль",
"expand-расширять",
"importance-важность",
"metal-металл",
"fat-жирный",
"ticket-билет",
"software-Программное обеспечение ",
"disappear-исчезать",
"corporate-корпоративный",
"strange-странный",
"lip-губа",
"reading-чтение",
"urban-городской",
"mental-умственный",
"increasingly-все больше и больше",
"lunch-второй завтрак",
"educational-образовательный",
"somewhere-где-нибудь !NEW!",
"farmer-фермер",
"sugar-сахар",
"planet-планета",
"favorite-любимый !NEW!",
"explore-исследовать",
"obtain-добиваться",
"enemy-враг",
"greatest-самый большой (от great)",
"complex-сложный",
"surround-окружать",
"athlete-спортсмен",
"invite-приглашать",
"repeat-твердить",
"carefully-осторожно",
"soul-душа",
"scientific-научный",
"impossible-невозможный",
"panel-комиссия",
"meaning-значение",
"mom-Мама",
"married-женатый",
"instrument-инструмент",
"predict-прогнозировать",
"weather-погода",
"presidential-президентских",
"emotional-эмоциональный",
"commitment-обязательство",
"Supreme-высший",
"bear-медведь",
"pocket-карман",
"thin-тонкий",
"temperature-температура",
"surprise-удивление",
"poll-подсчет (голосов)",
"proposal-предложение",
"consequence-следствие",
"breath-дыхание",
"sight-зрелище",
"balance-равновесие",
"adopt-принимать",
"minority-меньшинство",
"straight-прямо",
"connect-соединять",
"works-работает",
"teaching-обучение",
"belong-принадлежать",
"aid-помощь",
"advice-cовет",
"okay-Хорошо",
"photograph-фотография",
"empty-пустой",
"regional-региональный",
"trail-след (не trace)",
"novel-роман",
"code-код",
"somehow-как-нибудь",
"organize-организовывать",
"jury-присяжные",
"breast-грудь",
"Iraqi-иракский",
"acknowledge-признавать",
"theme-тема (не topic)",
"storm-буря",
"union-союз",
"desk-письменный стол",
"thanks-спасибо",
"fruit-фрукты",
"expensive-дорогой",
"yellow-желтый",
"conclusion-заключение",
"prime-главный (не chief",
"shadow-тень",
"struggle-бороться",
"conclude-завершать",
"analyst-аналитик",
"dance-танцевать",
"regulation-регулирование",
"being-будучи (от be)",
"ring-кольцо",
"largely-обильно *a-",
"shift-смена",
"revenue-доход",
"mark-норма",
"locate-определять местоположение !NEW!",
"county-графство",
"appearance-появление",
"package-пакет",
"difficulty-препятствие",
"bridge-мост",
"recommend-рекомендовать",
"obvious-очевидный o-",
"basically-в основном",
"e-mail",
"generate-порождать",
"anymore-больше не",
"propose-предлагать (не suggest)",
"thinking-размышление",
"possibly-возможно",
"trend-общее направление",
"visitor-гость",
"loan-заём",
"currently-В настоящее время ",
"comfortable-удобный",
"investor-инвестор",
"but-но",
"profit-прибыль",
"angry-сердитый",
"crew-судовая команда",
"accident-несчастный случай",
"meal-еда",
"hearing-слух",
"traffic-уличное движение",
"muscle-мышца",
"notion-понятие",
"capture-захват",
"prefer-предпочитать",
"truly-точно",
"earth-земля",
"Japanese-Японский",
"chest-грудь",
"thick-толстый",
"cash-деньги",
"museum-музей",
"beauty-красота",
"emergency-крайняя необходимость e-",
"unique-Уникальный ",
"internal-внутренний",
"ethnic-этнической",
"link-соединять",
"stress-стресс",
"content-содержание",
"select-выбирать",
"root-корень",
"nose-нос",
"declare-декларировать",
"appreciate-оценивать",
"actual-текущий",
"bottle-бутылка",
"hardly-едва (не barely",
"setting-окружение -ing",
"launch-начинать",
"file-картотека",
"sick-больной",
"outcome-результат",
"ad-объявление",
"defend-защищать",
"duty-долг",
"sheet-простыня",
"ought-долженствование",
"ensure-обеспечивать",
"Catholic-католик",
"extremely-крайне",
"extent-протяжение",
"component-компонент",
"mix-смешивать",
"slow-медленный",
"contrast-противоположность",
"zone-зона",
"wake-будить",
"airport-аэропорт",
"brown-коричневый",
"shirt-рубашка",
"pilot-пилот",
"warn-предупреждать w-",
"ultimately-В конечном счете ",
"cat-кошка",
"contribution-вклад",
"capacity-емкость",
"ourselves-себя",
"estate-поместье",
"guide-гид",
"circumstance-обстоятельство",
"snow-снег",
"English-английский язык",
"politician-политик",
"steal-(с)воровать",
"pursue-преследование",
"slip-скольжение",
"percentage-процент",
"meat-мясо",
"funny-смешной",
"neither-также не",
"soil-почва",
"surgery-хирургия",
"correct-исправлять",
"Jewish-иудейский",
"blame-считать виноватым",
"estimate-оценка",
"due-должный",
"basketball-баскетбол",
"golf-гольф",
"investigate-исследовать",
"crazy-безумный",
"significantly-значительно",
"chain-цепь",
"branch-ветвь",
"combination-комбинация",
"just-только",
"frequently-часто",
"governor-губернатор",
"relief-облегчение",
"user-потребитель",
"dad-папа",
"kick-пинать",
"manner-способ",
"ancient-древний",
"silence-молчание",
"rating-рейтинг",
"golden-золотой",
"motion-движение",
"German-Немецкий",
"gender-Пол",
"solve-(раз)решать",
"fee-гонорар",
"landscape-ландшафт",
"used-использованный",
"bowl-кубок",
"equal-равный",
"forth-вперед",
"frame-оправа",
"typical-типичный",
"except-исключая",
"conservative-консервативный",
"eliminate-исключать",
"host-хозяин",
"hall-зал",
"trust-доверять",
"ocean-океан",
"row-грести",
"producer-режиссер",
"afford-позволить себе",
"meanwhile-тем временем",
"regime-режим",
"division-деление",
"confirm-подтверждать",
"fix-починить",
"appeal-апелляция",
"mirror-зеркало",
"tooth-зуб",
"smart-изящный (не grace)",
"length-длина",
"entirely-совершенно",
"rely-полагаться",
"topic-тема",
"complain-жаловаться",
"variable-изменчивый",
"telephone-телефон",
"perception-восприятие",
"attract-привлекать",
"confidence-доверие",
"bedroom-спальня",
"secret-секрет",
"debt-долг",
"rare-редкий",
"his-его (-s)",
"tank-танк",
"nurse-няня (не nanny)",
"coverage-покрытие",
"opposition-противодействие",
"aside-в сторону",
"anywhere-где-нибудь !NEW!",
"bond-связь",
"pleasure-удовольствие",
"master-хозяин (не hoster)",
"era-эра",
"requirement-требование",
"fun-шутка",
"expectation-ожидание",
"wing-крыло",
"separate-отдельный",
"now-сейчас",
"somewhat-что-то",
"pour-лить",
"stir-суета",
"judgment-Суждение ",
"beer-пиво",
"reference-рекомендация",
"tear-слеза",
"doubt-сомнение",
"grant-дарить",
"seriously-серьезно",
"minister-министр",
"totally-полностью",
"hero-герой",
"industrial-промышленный",
"cloud-облако",
"stretch-растягивать",
"winner-победитель",
"volume-объем",
"seed-семя",
"surprised-удивленный",
"fashion-мода",
"pepper-перец",
"busy-занятый",
"intervention-посредничество",
"copy-копия",
"tip-чаевые",
"cheap-дешевый",
"aim-целиться",
"cite-цитировать",
"welfare-благосостояние",
"vegetable-овощ",
"gray-Серый ",
"dish-блюдо",
"beach-пляж",
"improvement-улучшение",
"everywhere-всюду",
"opening-начало",
"overall-всеобщий o-",
"divide-делить",
"initial-начальный",
"terrible-ужасный",
"oppose-оппонировать",
"contemporary-современный",
"route-маршрут",
"multiple-многократный -e",
"essential-обязательный",
"league-союз",
"criminal-преступник",
"careful-осторожный",
"core-сущность",
"upper-верхний",
"rush-устремляться",
"necessarily-обязательно",
"specifically-специфически",
"tired-усталый (от tire)",
"employ-держать на работе",
"holiday-отпуск",
"vast-обширный",
"resolution-решение",
"household-домашнее хозяйство",
"fewer-меньше",
"abortion-аборт",
"apart-в стороне",
"witness-свидетель",
"match-спичка",
"barely-только",
"sector-сектор",
"representative-представитель",
"beneath-под",
"beside-рядом",
"incident-инцидент",
"limited-ограниченный",
"proud-гордый",
"flow-течение",
"faculty-факультет",
"increased-вырос",
"waste-тратить",
"merely-единственно",
"mass-масса",
"emphasize-подчеркивать",
"experiment-эксперимент",
"definitely-Определенно ",
"bomb-бомба",
"enormous-громадный",
"tone-стиль",
"liberal-либеральный",
"massive-массивный",
"engineer-инженер",
"wheel-колесо",
"decline-опускаться",
"invest-вкладывать",
"cable-кабельный",
"towards-к",
"expose-выставлять",
"rural-сельская местность",
"AIDS-СПИД",
"Jew-еврей",
"narrow-узкий",
"cream-сливки",
"secretary-секретарь",
"gate-ворота",
"solid-твердый",
"hill-холм",
"typically-типично",
"noise-шум",
"grass-трава",
"unfortunately-к несчастью",
"hat-шляпа",
"legislation-законодательство",
"succeed-достигать цели",
"celebrate-праздновать",
"achievement-выполнение",
"fishing-рыбная ловля",
"accuse-обвинять",
"useful-полезный",
"reject-отвергать",
"talent-талант",
"taste-пробовать",
"characteristic-особенность",
"milk-молоко",
"escape-избежать",
"cast-бросать",
"sentence-предложение s-",
"unusual-необычный",
"closely-близко",
"convince-убеждать c-",
"height-высота",
"physician-врач",
"assess-оценить",
"plenty-изобилие",
"virtually-фактически",
"first-первый",
"addition-прибавление",
"sharp-точно",
"creative-творческий",
"lower-нижний",
"approve-одобрять",
"explanation-объяснение",
"gay-веселый g-",
"campus-кампус",
"proper-правильный",
"guilty-виноватый (g-)",
"acquire-приобретать",
"compete-состязаться",
"technical-технический",
"plus-плюс",
"immigrant-иммигрант",
"weak-слабый",
"illegal-нелегальный",
"hi-привет",
"alternative-альтернатива",
"interaction-взаимодействие",
"column-графа",
"personality-личность",
"signal-сигнал",
"curriculum-учебный план",
"honor-Честь ",
"passenger-пассажир",
"assistance-помощь",
"forever-вечно !NEW!",
"regard-взгляд",
"Israeli-израильтянин",
"association-ассоциация",
"twenty-двадцать",
"knock-стучать",
"wrap-завертывать",
"lab-лаборатория",
"display-показ",
"criticism-критика",
"asset-имущество",
"depression-уныние",
"spiritual-духовный",
"musical-музыкальный",
"journalist-журналист",
"prayer-молитва",
"suspect-подозревать",
"scholar-ученый",
"warning-предупреждение",
"climate-климат",
"cheese-сыр",
"observation-наблюдение",
"childhood-детство",
"payment-плата",
"sir-сэр",
"permit-разрешать",
"cigarette-сигарета",
"definition-определение",
"priority-приоритет",
"bread-хлеб",
"creation-создание (похоже на creature)",
"graduate-выпускник",
"request-просьба",
"emotion-возбуждение",
"scream-вскрикнуть",
"dramatic-драматический",
"universe-мир",
"gap-брешь",
"excellent-превосходный",
"deeply-глубоко",
"prosecutor-прокурор",
"lucky-счастливый",
"drag-тащить d-",
"airline-авиакомпания",
"library-библиотека",
"agenda-повестка дня",
"recover-выздоравливать",
"factory-завод",
"selection-отбор",
"primarily-в первую очередь",
"roof-крыша",
"unable-неспособный",
"expense-расход",
"initiative-инициатива",
"diet-диета",
"arrest-арестовывать",
"funding-финансирование",
"therapy-терапия",
"wash-мыть",
"schedule-расписание",
"sad-печальный",
"brief-короткий",
"housing-Корпус",
"post-почта",
"purchase-покупка",
"existing-Существующий -ing ",
"steel-сталь",
"regarding-Относительно *e-ing ",
"shout-кричать",
"remaining-осталось",
"visual-зрительный",
"fairly-довольно (не rather)",
"chip-обломок",
"violent-яростный v-",
"silent-молчаливый",
"suppose-полагать",
"self-сам",
"bike-велосипед",
"tea-чай",
"perceive-воспринимать",
"comparison-сравнение",
"settlement-поселение",
"layer-слой",
"planning-планирование",
"description-описание",
"slide-скользить",
"widely-широко",
"wedding-свадьба",
"inform-сообщать",
"portion-часть",
"territory-территория",
"immediate-непосредственный",
"opponent-соперник",
"abandon-отказываться",
"lake-озеро",
"transform-преобразование",
"tension-напряженность",
"leading-лидирование",
"bother-беспокойство",
"consist-состоять",
"alcohol-алкоголь",
"enable-давать возможность",
"bend-гнуться",
"saving-экономия -ing",
"desert-пустыня",
"shall-модальный глагол долженствования",
"error-ошибка",
"cop-полицейский",
"Arab-араб",
"double-двойной",
"sand-песок",
"Spanish-испанский",
"print-печатать",
"preserve-сохранять",
"passage-проход",
"formal-официальный",
"transition-переход",
"existence-существование",
"album-альбом",
"participation-участие",
"arrange-устраивать",
"atmosphere-атмосфера",
"joint-совместный",
"reply-отвечать",
"cycle-цикл",
"opposite-противоположный",
"lock-замок",
"deserve-заслуживать",
"consistent-совместимый",
"resistance-сопротивление",
"discovery-открытие",
"exposure-Подвергание ",
"pose-поза",
"stream-ручей",
"sale-распродажа",
"pot-котелок",
"grand-величественный",
"mine-мой (употребляется без последующего существительного)",
"hello-привет",
"coalition-коалиция",
"tale-повесть",
"knife-нож",
"resolve-решать",
"racial-расовый",
"phase-фаза",
"joke-шутка",
"coat-пальто",
"Mexican-мексиканец",
"symptom-симптом",
"manufacturer-производитель",
"philosophy-философия",
"potato-картофель",
"foundation-основание",
"quote-цитировать",
"online-онлайн",
"negotiation-Переговоры",
"urge-понуждать",
"occasion-случай",
"dust-пыль",
"breathe-дышать",
"elect-выбирать **e**",
"investigator-исследователь",
"jacket-куртка",
"glad-рад",
"ordinary-обычный",
"reduction-снижение",
"rarely-редко",
"pack-упаковывать",
"suicide-самоубийство",
"numerous-многочисленный",
"substance-вещество",
"discipline-дисциплина",
"elsewhere-В другом месте ",
"iron-железо",
"practical-практический",
"moreover-кроме того",
"passion-страсть",
"volunteer-доброволец",
"implement-выполнять",
"essentially-по существу",
"gene-ген",
"enforcement-правоприменение",
"vs-против",
"sauce-соус",
"independence-независимость",
"marketing-маркетинг",
"priest-священник",
"amazing-Удивительный -ing ",
"intense-интенсивный",
"advance-продвижение вперед",
"employer-наниматель",
"shock-удар s-",
"inspire-внушать",
"adjust-регулировать",
"retire-уходить",
"visible-видимый",
"kiss-целовать",
"illness-болезнь",
"cap-шапка",
"habit-привычка",
"competitive-конкурентоспособный",
"juice-сок",
"congressional-конгрессменов",
"involvement-участие",
"dominate-доминировать",
"previously-предварительно",
"whenever-когда бы ни",
"transfer-передача",
"analyze-анализировать",
"attach-придавать",
"for-для",
"disaster-бедствие",
"parking-стоянка",
"prospect-перспектива",
"boss-начальник",
"complaint-жалоба",
"championship-чемпионат",
"fundamental-фундаментальный",
"severe-суровый",
"enhance-усилить",
"mystery-тайна",
"impose-налагать",
"poverty-бедность",
"entry-вход",
"spending-расходы",
"king-король",
"evaluate-оценивать",
"symbol-символ",
"maker-производитель (m-)",
"mood-настроение",
"accomplish-выполнять",
"emphasis-подчеркивание",
"illustrate-иллюстрировать",
"boot-ботинок",
"monitor-монитор",
"Asian-азиатка",
"entertainment-развлечение",
"bean-боб",
"evaluation-оценка (не estimation)",
"creature-творение",
"commander-командир",
"digital-цифровой",
"arrangement-договоренность",
"concentrate-сосредотачиваться",
"usual-обыкновенный",
"anger-гнев",
"psychological-психологический",
"heavily-тяжело",
"peak-вершина",
"approximately-приблизительно",
"increasing-возрастающий",
"disorder-беспорядок",
"missile-ракета",
"equally-поровну",
"vary-отличаться",
"wire-переводить телеграфом (деньги)",
"round-круг",
"distribution-распределение",
"transportation-перевозка",
"holy-священный",
"twin-двойной",
"command-приказ",
"commission-комиссионные",
"interpretation-интерпретация",
"breakfast-завтрак",
"strongly-решительно (первая буква НЕ d)",
"engineering-техника",
"luck-удача",
"constant-постоянный",
"clinic-клиника",
"veteran-ветеран",
"smell-запах",
"tablespoon-столовая ложка",
"capable-способный",
"nervous-нервный",
"tourist-турист(ский)",
"toss-толчок",
"crucial-ключевой",
"bury-хоронить",
"pray-молить",
"tomato-томат",
"exception-исключение",
"butter-масло",
"deficit-дефицит",
"bathroom-ванная комната",
"objective-цель",
"electronic-электронный",
"ally-союзник",
"journey-путешествие",
"reputation-репутация",
"mixture-микстура",
"surely-несомненно",
"tower-башня",
"smoke-курить",
"confront-стоять против",
"pure-чистый",
"glance-взглянуть",
"dimension-измерение",
"toy-игрушка",
"prisoner-заключенный",
"fellow-человек",
"smooth-гладкий",
"nearby-поблизости (nearby)",
"peer-вглядываться",
"designer-конструктор",
"personnel-персонал",
"educator-воспитатель",
"relative-родственник",
"immigration-иммиграция",
"belt-пояс",
"teaspoon-чайная ложка",
"birthday-день рождения",
"implication-импликация",
"perfectly-совершенно",
"coast-побережье",
"supporter-сторонник",
"accompany-сопровождать",
"silver-серебро",
"teenager-подросток",
"recognition-узнавание",
"retirement-отставка",
"flag-флаг",
"recovery-выздоровление",
"whisper-шепот",
"gentleman-господин",
"corn-кукуруза",
"moon-луна",
"inner-внутренний",
"junior-младший",
"throat-горло",
"salary-оклад",
"swing-качание",
"observer-наблюдатель",
"publication-публикация",
"crop-урожай",
"dig-копать",
"permanent-постоянный",
"phenomenon-явление",
"anxiety-тревога",
"unlike-непохожий",
"wet-мокрый",
"literally-буквально",
"resist-сопротивляться",
"convention-собрание",
"embrace-обнимать",
"assist-помочь",
"exhibition-выставка",
"construct-строить",
"viewer-зритель",
"pan-сковорода",
"consultant-консультант",
"administrator-администратор",
"occasionally-изредка",
"mayor-мэр",
"consideration-рассмотрение",
"CEO-Исполнительный директор",
"secure-страховать s-",
"pink-розовый",
"buck-доллар",
"historic-исторический",
"poem-стихотворение",
"grandmother-бабушка",
"bind-связывать (не link)",
"fifth-пятый",
"constantly-постоянно",
"enterprise-предприятие",
"favor-Польза(покровительство) ",
"testing-испытание",
"stomach-живот",
"apparent-видимый",
"weigh-взвешивать",
"install-водворять",
"sensitive-чувствительный",
"suggestion-предложение",
"mail-почта",
"recipe-рецепт",
"reasonable-разумный r-",
"preparation-приготовление",
"wooden-деревянный",
"elementary-элементарный",
"concert-концерт",
"aggressive-агрессивный",
"FALSE-ЛОЖНЫЙ",
"intention-намерение",
"channel-канал",
"extreme-чрезвычайный",
"tube-труба (не pipe)",
"drawing-протаскивание",
"protein-белок",
"quit-прекращать",
"absence-отсутствие",
"Latin-латинский",
"rapidly-быстро",
"jail-тюрьма",
"diversity-разнообразие",
"honest-честный",
"Palestinian-палестинец",
"pace-шагать",
"employment-служба",
"speaker-оратор",
"impression-впечатление",
"essay-очерк",
"respondent-ответчик",
"giant-гигант",
"cake-торт",
"historian-историк",
"negotiate-договариваться",
"restore-восстанавливать",
"substantial-существенный",
"pop-поп",
"specialist-специалист",
"origin-происхождение",
"approval-одобрение",
"quietly-тихо",
"advise-советовать",
"conventional-обычный",
"depth-глубина",
"wealth-богатство",
"disability-инвалидность",
"shell-раковина",
"criticize-критиковать",
"effectively-фактически",
"biological-биологический",
"onion-лук",
"deputy-депутат",
"flat-квартира",
"brand-головня",
"assure-уверять",
"mad-обезумевший",
"award-награда",
"criteria-критерии",
"dealer-дилер",
"via-через",
"utility-полезность",
"precisely-точно",
"arise-возникать",
"armed-вооруженный",
"nevertheless-тем не менее",
"highway-большая дорога",
"clinical-клиническая",
"routine-рутинный",
"wage-заработная плата",
"normally-обычно n-",
"phrase-фраза",
"ingredient-составная часть",
"stake-ставка",
"Muslim-мусульманка",
"fiber-волокно",
"activist-активист",
"Islamic-исламский",
"snap-щелкать (snap)",
"terrorism-терроризм",
"refugee-беженец",
"incorporate-инкорпорировать",
"hip-ягода шиповника",
"ultimate-последний",
"switch-переключать",
"corporation-корпорация",
"valuable-ценный",
"assumption-предположение",
"gear-механизм",
"barrier-барьер",
"minor-младший",
"provision-заготовка",
"killer-убийца",
"assign-назначать",
"gang-шайка",
"developing-развивающийся",
"classic-классический",
"chemical-химический",
"label-этикетка",
"teen-подросток",
"index-индекс",
"vacation-отпуск",
"advocate-отстаивать",
"draft-чертеж",
"extraordinary-необычный",
"heaven-небо",
"rough-грубый",
"yell-пронзительный крик",
"pregnant-беременная",
"distant-дальний",
"drama-драма",
"satellite-спутник",
"personally-лично",
"clock-часы (не watch)",
"chocolate-шоколад",
"Italian-итальянский",
"Canadian-канадец",
"ceiling-потолок",
"sweep-(под)мести s-",
"advertising-реклама",
"universal-всеобщий",
"spin-прясть",
"button-кнопка",
"bell-звонок (b-)",
"rank-ряд",
"darkness-темнота",
"clothing-одежда",
"super-супер",
"yield-приносить y-",
"fence-забор",
"portrait-портрет",
"survival-выживание",
"roughly-грубо",
"lawsuit-судебный процесс",
"testimony-свидетельство",
"bunch-связка",
"found-нашел",
"burden-груз",
"react-реагировать",
"chamber-палата",
"furniture-мебель",
"cooperation-сотрудничество",
"string-вереница",
"ceremony-церемония",
"communicate-сообщать",
"cheek-щека",
"lost-потерял",
"profile-профиль",
"mechanism-устройство",
"disagree-не соглашаться",
"penalty-штраф",
"ie-т.е.",
"resort-обращение",
"destruction-разрушение",
"unlikely-маловероятный",
"tissue-ткань",
"constitutional-конституционная",
"pant-задыхаться (не gasp)",
"stranger-незнакомец",
"infection-инфекционное заболевание",
"cabinet-кабинет (не parlour)",
"broken-разбитый",
"apple-яблоко",
"electric-электрический",
"proceed-продолжать",
"bet-держать пари",
"literary-литературный",
"virus-вирус",
"stupid-глупый",
"dispute-диспут",
"fortune-удача",
"strategic-стратегическое",
"assistant-помощник",
"overcome-преодолеть",
"remarkable-замечательный  r-",
"occupy-занимать",
"statistics-статистика",
"shopping-делать покупки",
"cousin-двоюродный брат",
"encounter-встретить",
"wipe-вытирать",
"initially-вначале i-",
"blind-слепой",
"port-порт",
"electricity-электричество",
"genetic-генетический",
"adviser-консультант",
"spokesman-представитель",
"retain-удерживать",
"latter-последний",
"incentive-стимул",
"slave-раб",
"translate-переводить",
"accurate-точный",
"whereas-тогда как",
"terror-ужас t-",
"expansion-расширение",
"elite-элита",
"Olympic-олимпийский",
"dirt-грязь",
"odd-странный",
"rice-рис",
"bullet-пуля",
"tight-плотный",
"Bible-библия",
"chart-диаграмма",
"solar-солнечный",
"square-площадь",
"concentration-концентрация",
"complicated-сложный",
"gently-мягко",
"champion-чемпион",
"scenario-сценарий",
"telescope-телескоп",
"reflection-отражение",
"revolution-революция",
"strip-полоса",
"interpret-интерпретировать",
"friendly-дружеский",
"tournament-турнир",
"fiction-фантастика",
"detect-открывать",
"tremendous-громадный",
"lifetime-продолжительность жизни",
"recommendation-рекомендация",
"senator-сенатор",
"hunting-охота",
"salad-салат",
"guarantee-гарантия",
"innocent-наивный",
"boundary-граница *o-",
"pause-пауза",
"remote-дистанционный",
"satisfaction-удовлетворение",
"journal-журнал j-",
"bench-скамейка",
"lover-любитель",
"raw-сырой",
"awareness-осознание",
"surprising-удивительный",
"withdraw-брать назад",
"deck-палуба",
"similarly-также",
"newly-вновь (не again)",
"pole-полюс",
"testify-давать показания",
"mode-способ",
"dialogue-диалог",
"imply-подразумевать",
"naturally-естественно",
"mutual-взаимный",
"founder-основатель",
"advanced-передовой",
"pride-гордость",
"dismiss-увольнять",
"aircraft-самолет",
"delivery-доставка",
"mainly-главным образом",
"bake-выпекать",
"freeze-замерзать",
"platform-платформа",
"finance-финансы",
"sink-тонуть",
"attractive-привлекательный",
"diverse-разный",
"relevant-Соответствующий",
"ideal-идеал",
"joy-радость",
"regularly-регулярно",
"working-делающий",
"singer-певец",
"evolve-эволюционировать",
"shooting-Стрельба ",
"partly-частично",
"unknown-неизвестный",
"offense-преступление",
"counter-прилавок",
"DNA-ДНК",
"potentially-потенциально",
"thirty-тридцать",
"justify-обосновывать",
"protest-протестовать",
"crash-потерпеть крах",
"craft-искусство",
"treaty-договор",
"terrorist-террорист",
"insight-в поле зрения",
"possess-обладать",
"politically-политически",
"tap-постучать",
"extensive-обширный",
"episode-эпизод",
"swim-плавать",
"tire-уставать",
"fault-вина",
"loose-свободный",
"shortly-вскоре",
"originally-первоначально",
"considerable-значительный c-",
"prior-прежний",
"intellectual-интеллигент",
"assault-нападать",
"relax-ослаблять",
"stair-лестница",
"adventure-рисковать",
"external-наружный",
"proof-доказательство",
"confident-уверенный",
"headquarters-штаб",
"sudden-внезапный",
"dirty-грязный",
"violation-нарушение",
"tongue-язык",
"license-давать разрешение",
"shelter-приют",
"rub-тереть",
"controversy-полемика",
"entrance-вход",
"properly-правильно",
"fade-увядать",
"defensive-оборонительный",
"tragedy-трагедия",
"net-сеть",
"characterize-охарактеризовать",
"funeral-похороны",
"profession-профессия",
"alter-изменять",
"constitute-назначать",
"establishment-установление",
"squeeze-выжимать",
"imagination-воображение",
"mask-маска",
"convert-превращать",
"comprehensive-исчерпывающий",
"prominent-выдающийся",
"presentation-презентация",
"regardless-независимо от",
"load-нагрузка",
"stable-конюшня",
"introduction-введение",
"pretend-притворяться",
"not-не",
"elderly-пожилой",
"representation-изображение",
"deer-олень",
"split-раскалывать",
"violate-нарушать",
"partnership-партнерство",
"pollution-загрязнение",
"emission-излучение",
"steady-прочный",
"vital-жизненный",
"fate-судьба",
"earnings-прибыль",
"oven-печь",
"distinction-различие",
"segment-Доля (не portion",
"nowhere-нигде",
"poet-поэт",
"mere-простой",
"exciting-волнующий",
"variation-Изменение(разновидность) ",
"comfort-удобство",
"radical-радикал",
"adapt-приспособить",
"Irish-ирландский",
"honey-мед",
"correspondent-корреспондент",
"pale-бледный",
"musician-музыкант",
"significance-значение",
"vessel-сосуд",
"storage-хранение *t-",
"flee-бежать",
"mm-Мм ",
"leather-кожа",
"distribute-распределять",
"evolution-Развитие ",
"ill-больной",
"tribe-племя",
"shelf-полка",
"can-уметь",
"grandfather-дедушка",
"lawn-лужайка",
"buyer-покупатель",
"dining-обеденный",
"wisdom-мудрость",
"council-совет",
"vulnerable-уязвимый",
"instance-пример",
"garlic-чеснок",
"capability-возможность",
"poetry-поэзия",
"celebrity-известность",
"gradually-постепенно",
"stability-устойчивость",
"fantasy-воображение",
"scared-напуганный !NEW!",
"plot-заговор",
"framework-каркас",
"gesture-жест",
"depending-в зависимости",
"ongoing-постоянный",
"psychology-психология",
"counselor-консультант",
"chapter-глава (книги)",
"divorce-развод",
"owe-быть должным",
"pipe-труба (не tube)",
"athletic-Спортивное",
"slight-проявление пренебрежительного равнодушия;неуважение",
"math-математический",
"shade-оттенок",
"tail-конец",
"sustain-поддерживать (*u-)",
"mount-взбираться m-",
"obligation-обязательство",
"angle-угол",
"palm-ладонь",
"differ-различать",
"custom-обычай",
"economist-экономист",
"fifteen-пятнадцать",
"soup-суп",
"celebration-празднование",
"efficient-эффективный",
"composition-сочинение",
"satisfy-удовлетворять",
"pile-куча",
"briefly-кратко",
"carbon-углерод",
"closer-ближе",
"consume-потреблять",
"scheme-проект",
"crack-попытка",
"frequency-частота",
"tobacco-табак",
"survivor-уцелевший",
"besides-кроме",
"psychologist-психолог",
"wealthy-богатый (w-)",
"galaxy-Галактика ",
"given-данный (от give)",
"ski-ходить на лыжах",
"limitation-ограничение",
"OK-все в порядке",
"trace-следить",
"appointment-условленная встреча *pp*...",
"preference-предпочтение",
"meter-счетчик",
"explosion-взрыв",
"publicly-публично",
"incredible-невероятно",
"fighter-истребитель",
"rapid-быстрый r-",
"admission-допуск",
"hunter-охотник",
"educate-воспитывать",
"painful-причиняющий боль",
"friendship-дружба -ship",
"aide-помощник",
"infant-младенец",
"calculate-рассчитывать",
"fifty-пятьдесят",
"rid-освобождать",
"porch-крыльцо",
"tendency-тенденция",
"uniform-форма",
"formation-образование",
"scholarship-ученость",
"reservation-предварительный заказ",
"efficiency-эффективность",
"qualify-квалифицировать",
"mall-торговый центр",
"derive-выводить",
"scandal-скандал",
"PC-ПК",
"helpful-полезный h-",
"impress-производить впечатление",
"heel-пятка",
"resemble-походить",
"privacy-уединенность",
"fabric-ткань",
"contest-спор",
"proportion-пропорция",
"guideline-директива",
"rifle-ружье",
"maintenance-поддержание",
"conviction-осуждение",
"trick-хитрость",
"organic-органический",
"tent-палатка",
"examination-экзамен",
"publisher-издатель",
"strengthen-усиливать",
"proposed-Предложенный ",
"myth-миф",
"sophisticated-сложный",
"cow-корова",
"etc-И т.д ",
"standing-репутация",
"asleep-спящий (не sleepy)",
"tennis-теннис",
"nerve-нерв",
"barrel-баррель",
"bombing-бомбардировка",
"membership-членство",
"ratio-соотношение",
"menu-меню",
"controversial-спорный",
"desperate-отчаянный",
"lifestyle-Стиль жизни",
"humor-юмор",
"loud-громкий",
"glove-перчатка",
"sufficient-достаточный",
"narrative-повествование",
"photographer-фотограф",
"helicopter-вертолет",
"modest-скромный m-",
"provider-поставщик",
"delay-отсрочка",
"agricultural-сельскохозяйственный",
"explode-взрывать",
"stroke-удар",
"scope-пределы",
"punishment-наказание",
"handful-горсть",
"badly-сильно",
"horizon-горизонт",
"curious-любознательный",
"downtown-в центре города",
"girlfriend-Подруга",
"prompt-проворный",
"cholesterol-холестерин",
"absorb-поглощать",
"adjustment-регулирование *d-",
"taxpayer-налогоплательщик",
"eager-нетерпеливый",
"principal-главный",
"detailed-детальный",
"motivation-мотивация",
"assignment-назначение",
"restriction-ограничение",
"laboratory-лаборатория",
"workshop-мастерская",
"differently-По-другому ",
"auto-автомобиль",
"romantic-романтичный",
"cotton-хлопок",
"motor-мотор",
"sue-преследовать судебным порядком",
"flavor-аромат",
"overlook-надзирать",
"float-плавать",
"undergo-испытывать",
"sequence-последовательность",
"demonstration-демонстрация",
"jet-струя (воды",
"orange-апельсин",
"consumption-потребление",
"assert-утверждать",
"blade-лезвие",
"temporary-временный",
"medication-лечение",
"cabin-каюта",
"bite-кусаться",
"edition-издание",
"valley-долина",
"yours-ваш",
"pitch-бросок",
"pine-сосна",
"brilliant-блестящий",
"versus-против",
"manufacturing-производство",
"absolute-совершенный",
"chef-шеф",
"discrimination-дискриминация",
"offensive-наступление",
"boom-бум",
"register-(за)регистрировать",
"appoint-назначать",
"heritage-наследие",
"God-Бог",
"dominant-доминирующий",
"successfully-успешно",
"shit-дерьмо",
"lemon-лимон",
"hungry-голодный (не от слова starve)",
"wander-бродить",
"submit-подчиняться",
"economics-экономика",
"naked-обнаженный",
"anticipate-предвидеть",
"nut-орех",
"legacy-наследство",
"extension-расширение",
"shrug-пожимать плечами",
"battery-аккумулятор",
"arrival-прибытие",
"legitimate-обоснованный",
"orientation-ориентация",
"inflation-инфляция",
"cope-справиться",
"flame-пламя (не blaze)",
"cluster-гроздь; скопляться",
"wound-рана",
"dependent-зависимый",
"shower-душ",
"institutional-институциональных",
"depict-изображать",
"operating-управляющий -ing",
"flesh-тело",
"garage-гараж",
"operator-оператор",
"instructor-инструктор",
"collapse-крушение",
"borrow-брать в долг",
"furthermore-кроме того",
"comedy-комедия",
"mortgage-заклад",
"sanction-санкция",
"civilian-гражданский",
"twelve-двенадцать",
"weekly-еженедельный",
"habitat-естественная среда",
"grain-зерно",
"brush-щетка",
"consciousness-сознание",
"devote-посвящать",
"measurement-измерение",
"province-провинция",
"ease-покой",
"seize-хватать -e",
"ethics-этика",
"nomination-назначение",
"permission-разрешение",
"wise-мудрый",
"actress-актриса",
"summit-вершина",
"acid-кислый",
"odds-разница",
"gifted-одаренный",
"frustration-расстройство",
"medium-средство",
"physically-физически",
"distinguish-отличать",
"shore-берег",
"repeatedly-неоднократно",
"lung-легкое",
"running-пробег",
"distinct-отдельный (не separate",
"artistic-художественный",
"discourse-речь",
"basket-корзина",
"ah-ах",
"fighting-бой",
"impressive-впечатляющий -ve",
"competitor-конкурент",
"ugly-уродливый",
"worried-волновался",
"portray-изображать",
"powder-пудра",
"ghost-привидение",
"persuade-убеждать",
"moderate-умеренный",
"subsequent-последующий (не successive)",
"continued-продолжал (от continue)",
"cookie-печенье",
"carrier-носильщик",
"cooking-Готовка",
"frequent-частый",
"ban-запрещать",
"awful-ужасный",
"admire-восхищаться",
"pet-любимое домашнее животное",
"miracle-чудо",
"exceed-превышать",
"rhythm-ритм",
"widespread-широко распространен",
"killing-убийственный (-ing)",
"lovely-прекрасный",
"sin-грех",
"charity-милосердие",
"script-сценарий",
"tactic-тактика",
"identification-отождествление",
"transformation-преобразование",
"everyday-повседневный",
"headline-заголовок",
"venture-предприятие",
"invasion-вторжение",
"nonetheless-тем не менее",
"adequate-достаточный",
"piano-пианино",
"grocery-продуктовый",
"intensity-интенсивность",
"exhibit-экспонат",
"blanket-одеяло",
"margin-минимум",
"quarterback-защитник",
"mouse-мышь",
"rope-канат",
"concrete-бетон",
"prescription-рецепт",
"chase-охотиться",
"brick-кирпич",
"recruit-вербовать",
"patch-заплатка",
"consensus-консенсус",
"horror-ужас h-",
"recording-регистрация -ing",
"changing-Изменение(замена) ",
"painter-художник",
"colonial-колониальный",
"pie-пирог",
"sake-ради",
"gaze-пристально глядеть",
"courage-мужество",
"pregnancy-беременность",
"swear-клясться",
"defeat-поражение",
"clue-ключ (к разгадке)",
"reinforce-усиливать",
"confusion-смущение",
"slice-ломоть",
"occupation-занятие",
"dear-дорогой",
"coal-уголь",
"sacred-священный",
"formula-формула",
"cognitive-познавательный",
"collective-коллектив",
"exact-точный",
"uncle-дядя",
"captain-капитан",
"sigh-вздыхать",
"attribute-приписывать",
"dare-сметь",
"homeless-бездомный",
"gallery-галерея",
"soccer-футбольный",
"defendant-ответчик",
"tunnel-тоннель",
"fitness-годность",
"lap-подол",
"grave-могила",
"toe-палец",
"container-контейнер",
"virtue-добродетель",
"abroad-за границей",
"architect-архитектор",
"dramatically-драматично",
"makeup-составить",
"inquiry-расспросы",
"rose-роза",
"surprisingly-удивительно",
"highlight-основной момент",
"decrease-уменьшать",
"indication-индикация",
"rail-рельс",
"anniversary-годовщина",
"couch-кушетка",
"alliance-союз",
"hypothesis-Гипотеза ",
"boyfriend-дружок",
"compose-сочинять",
"mess-беспорядок",
"legend-легенда",
"regulate-регулировать",
"adolescent-подросток",
"shine-сиять",
"norm-норма",
"upset-беспорядок",
"remark-замечать",
"resign-уходить в отставку",
"reward-награда",
"gentle-нежный",
"related-Связанный",
"organ-орган",
"lightly-слегка !NEW!",
"concerning-относительно (не relatively) -ing",
"invent-изобретать",
"laughter-смех",
"northwest-северо",
"counseling-консультирование",
"receiver-приемник",
"ritual-ритуал",
"insect-насекомое",
"interrupt-прерывать",
"salmon-лосось",
"trading-торговля",
"magic-волшебный m-",
"superior-высший",
"combat-бой",
"stem-стержень",
"surgeon-хирург",
"acceptable-приемлемо",
"physics-физика",
"rape-изнасилование",
"counsel-обсуждение",
"jeans-джинсы",
"hunt-охотиться",
"continuous-непрерывный",
"log-бревно",
"echo-эхо",
"pill-пилюля",
"excited-взволнованный",
"sculpture-скульптура",
"compound-составной -u**",
"integrate-интегрировать",
"flour-мука",
"bitter-горький",
"bare-голый",
"slope-склон",
"rent-брать напрокат",
"presidency-президентство",
"serving-порция s-ing",
"subtle-тонкий",
"greatly-очень",
"bishop-епископ",
"drinking-питьевой",
"acceptance-принятие",
"pump-насос",
"candy-конфеты",
"evil-зло",
"pleased-довольный",
"medal-медаль",
"beg-просить",
"sponsor-спонсор",
"ethical-этический",
"secondary-средний",
"slam-хлопать",
"export-экспорт",
"experimental-экспериментальный",
"melt-таять",
"midnight-полночь",
"curve-изгиб",
"integrity-целостность",
"entitle-давать право",
"evident-очевидный",
"logic-логика",
"essence-сущность",
"exclude-исключать",
"harsh-грубый",
"closet-чулан",
"suburban-пригородный",
"greet-приветствовать",
"interior-внутренний (не internal)",
"corridor-коридор",
"retail-розничная торговля",
"pitcher-подающий",
"march-маршировать",
"snake-змея",
"excuse-извинять",
"weakness-слабость",
"pig-свинья",
"classical-классический",
"estimated-предполагаемый",
"T-shirt",
"unemployment-безработица",
"civilization-цивилизация",
"fold-складывать",
"reverse-противоположное",
"missing-недостающий",
"correlation-Корреляция ",
"humanity-человечество",
"flash-вспышка",
"developer-развивающийся (о человеке) !NEW!",
"reliable-надежный",
"excitement-возбуждение",
"beef-говядина",
"Islam-ислам",
"Roman-Римский",
"architecture-архитектура",
"occasional-случайный",
"administrative-административный",
"elbow-локоть",
"deadly-смертельно",
"Hispanic-латиноамериканец",
"allegation-утверждение",
"confuse-смущать",
"airplane-самолет",
"monthly-(еже)месячный",
"duck-утка",
"dose-доза",
"Korean-Корейский",
"plead-умолять",
"initiate-начинать (не commence)",
"lecture-лекция",
"van-фургон",
"sixth-шестой",
"bay-бухта",
"mainstream-Основной поток",
"suburb-пригород",
"sandwich-бутерброд",
"trunk-ствол",
"rumor-слух",
"implementation-Выполнение ",
"swallow-глотать",
"motivate-мотивировать",
"render-отдавать",
"longtime-много времени",
"trap-ловушка",
"restrict-ограничивать",
"cloth-ткань",
"seemingly-по",
"legislative-законодательные",
"effectiveness-эффективность",
"enforce-принуждать",
"lens-линза",
"inspector-контролер",
"lend-дать в долг",
"plain-ясный",
"fraud-обман",
"companion-товарищ",
"contend-бороться",
"nail-ноготь",
"array-массив",
"strict-точный",
"assemble-созывать",
"frankly-откровенно",
"rat-крыса",
"burst-заливаться",
"hallway-прихожая",
"cave-пещера",
"inevitable-неизбежный",
"southwest-к юго",
"monster-чудовище",
"unexpected-неожиданный",
"obstacle-препятствие",
"facilitate-облегчать",
"rip-рвать",
"herb-трава",
"overwhelming-несметный",
"integration-интеграция",
"crystal-хрусталь",
"recession-спад",
"written-письменный",
"motive-повод",
"flood-наводнение",
"pen-ручка",
"ownership-собственность",
"nightmare-кошмар",
"inspection-осмотр",
"supervisor-руководитель",
"consult-советоваться",
"arena-арена",
"diagnosis-диагностика",
"possession-владение",
"forgive-прощать",
"consistently-последовательно",
"basement-основание",
"drift-сносить",
"drain-вытекание",
"prosecution-судебное преследование",
"maximum-Максимум ",
"announcement-объявление",
"warrior-воин (w-)",
"prediction-предсказание",
"bacteria-бактерии",
"questionnaire-анкета",
"mud-грязь",
"infrastructure-инфраструктура",
"hurry-спешить",
"privilege-привилегия",
"temple-храм",
"outdoor-на открытом воздухе",
"suck-сосать",
"and/or-и / или",
"broadcast-передача по радио",
"re-ре",
"leap-високосный",
"random-случайный",
"wrist-наручный",
"curtain-занавеска",
"pond-пруд (не pool)",
"domain-Область ",
"guilt-вина",
"cattle-(рогатый) скот",
"walking-гуляющий",
"playoff-плей",
"minimum-минимум",
"fiscal-фискальный",
"skirt-юбка",
"dump-разгружать",
"hence-следовательно",
"database-База данных ",
"uncomfortable-неудобный u-",
"execute-выполнять e-",
"limb-конечность (анат.)",
"ideology-идеология",
"tune-мотив",
"continuing-продолжающийся",
"harm-беда",
"railroad-железная дорога",
"endure-Вынести ",
"radiation-излучение",
"horn-рог",
"chronic-хронический",
"peaceful-мирный",
"innovation-инновация",
"strain-натягивать",
"guitar-гитара",
"replacement-замещение",
"behave-вести себя",
"administer-управлять",
"simultaneously-одновременно",
"dancer-танцор",
"amendment-поправка",
"pad-мягкая прокладка",
"transmission-передача",
"await-ждать",
"retired-отставной",
"trigger-курок",
"spill-проливать(ся)",
"grateful-благодарный g-",
"grace-грация",
"virtual-фактический",
"colony-колония",
"adoption-принятие",
"indigenous-местный",
"closed-закрыл",
"convict-признать виновным",
"towel-полотенце",
"modify-модифицировать",
"particle-частица",
"prize-приз",
"landing-высадка на берег -ing",
"boost-повышение",
"bat-бить",
"alarm-тревога",
"festival-праздник",
"grip-схватывание",
"weird-судьба",
"undermine-подрывать",
"freshman-первокурсник",
"sweat-пот",
"outer-внешний",
"drunk-выпитый",
"separation-отделение",
"traditionally-традиционно",
"govern-управлять g-",
"southeast-юго",
"intelligent-умный",
"wherever-где бы ни",
"ballot-голосование",
"rhetoric-риторика",
"convinced-убежденный",
"driving-езда",
"vitamin-витамин",
"enthusiasm-энтузиазм",
"accommodate-согласовывать",
"praise-хвалить",
"injure-ушибиться -e",
"wilderness-пустыня",
"endless-бесконечный",
"mandate-мандат",
"respectively-соответственно",
"uncertainty-неопределенность",
"chaos-хаос",
"mechanical-механический",
"canvas-холст",
"forty-сорок",
"lobby-вестибюль",
"profound-глубокий",
"format-формат",
"trait-черта",
"currency-валюта",
"turkey-индейка",
"reserve-заказывать",
"beam-сиять",
"astronomer-астроном",
"corruption-продажность",
"contractor-подрядчик",
"apologize-извиняться",
"doctrine-Доктрина ",
"genuine-подлинный",
"thumb-большой палец (руки)",
"unity-единство",
"compromise-компромисс",
"horrible-ужасный h-",
"behavioral-поведенческий",
"exclusive-исключительный",
"scatter-разбрасывать",
"commonly-обыкновенно",
"convey-перевозить",
"twist-вить(ся)",
"complexity-сложность",
"fork-вилка",
"disk-Диск ",
"relieve-облегчать",
"suspicion-подозрение",
"residence-резиденция",
"shame-стыд",
"meaningful-значимым",
"sidewalk-тротуар",
"Olympics-Олимпийские игры",
"technological-технологический",
"signature-подпись",
"pleasant-приятный",
"wow-Ничего себе ",
"suspend-приостанавливать",
"rebel-бунтарь",
"frozen-замороженный",
"spouse-супруг",
"fluid-жидкий",
"pension-пенсия",
"resume-итог",
"theoretical-теоретический",
"sodium-натрий",
"promotion-поощрение",
"delicate-изящный d-",
"forehead-лоб",
"rebuild-перестраивать",
"bounce-отскакивать",
"electrical-электрический",
"hook-крючок",
"detective-детектив(ный)",
"traveler-путешественник",
"click-щелкать",
"compensation-компенсация",
"exit-выход",
"attraction-привлекательность",
"dedicate-посвящать",
"altogether-всего",
"pickup-подбирать",
"carve-вырезать",
"needle-игла",
"belly-живот",
"scare-испуг",
"portfolio-портфолио",
"shuttle-челнок",
"invisible-невидимый",
"timing-синхронизация",
"engagement-занятие *n-",
"ankle-щиколотка",
"transaction-дело",
"rescue-спасение",
"counterpart-копия",
"historically-исторически",
"firmly-твердо",
"mild-мягкий (не soft)",
"rider-наездник",
"doll-кукла",
"noon-полдень",
"amid-между",
"identical-тождественный",
"precise-точный",
"anxious-беспокойный *n-",
"structural-структурный",
"residential-жилой",
"diagnose-диагностики",
"carbohydrate-углевод",
"liberty-свобода",
"poster-плакат",
"theology-теология",
"nonprofit-некоммерческий",
"crawl-ползать (не creep)",
"oxygen-кислород",
"handsome-красивый",
"sum-сумма",
"provided-при условии",
"businessman-бизнесмен",
"promising-многообещающий -ing",
"conscious-сознающий",
"determination-решимость",
"donor-донор",
"hers-ее",
"pastor-пастор",
"jazz-джаз",
"opera-опера",
"acquisition-приобретение",
"pit-яма",
"hug-крепко обнимать",
"wildlife-живая природа",
"punish-наказывать",
"equity-капитал",
"doorway-дверной проем !NEW!",
"departure-отъезд",
"elevator-лифт",
"teenage-подростковый",
"guidance-руководство",
"happiness-счастье",
"statue-статуя",
"pursuit-преследование",
"repair-ремонтировать",
"decent-приличный",
"gym-Гимнастический зал",
"oral-пероральный",
"clerk-чиновник",
"envelope-конверт",
"reporting-Сообщение -ing ",
"destination-место назначения",
"fist-кулак",
"endorse-одобрять",
"exploration-исследование",
"generous-великодушный",
"bath-ванна",
"thereby-таким образом t-",
"indicator-индикатор",
"sunlight-солнечный свет",
"feedback-Обратная связь",
"spectrum-спектр",
"purple-лиловый",
"laser-лазер",
"bold-смелый (не dare)",
"reluctant-делающий что-л. с большой неохотой",
"starting-начало",
"expertise-экспертиза",
"practically-практический",
"eating-прием пищи",
"hint-намек",
"sharply-резко",
"parade-парад",
"realm-Царство ",
"cancel-отменить",
"blend-смешивать",
"therapist-Терапевт",
"peel-чистить",
"pizza-пицца",
"recipient-получатель",
"hesitate-колебаться",
"flip-кувырок",
"accounting-учет",
"bias-смещение",
"huh-хм",
"metaphor-метафора",
"candle-свеча",
"judicial-судебная",
"entity-организация",
"suffering-страдание",
"lamp-лампа",
"garbage-мусор",
"servant-слуга",
"regulatory-регулятивный",
"diplomatic-дипломатичный",
"elegant-изящный",
"reception-прием",
"vanish-исчезать",
"automatically-автоматически",
"chin-подбородок",
"necessity-необходимость",
"confess-признавать",
"racism-расизм",
"starter-стартер",
"banking-банковское дело",
"casual-случайный (не random)",
"gravity-серьезность",
"enroll-зачислять",
"diminish-уменьшить",
"prevention-профилактика",
"minimize-минимизировать",
"chop-нарубить",
"performer-исполнитель",
"intent-намерение",
"isolate-изолировать",
"inventory-опись",
"productive-продуктивный",
"assembly-собрание",
"civic-гражданский",
"silk-шелковый",
"magnitude-величина",
"steep-крутой (не sharp)",
"hostage-заложник",
"collector-сборщик",
"popularity-популярность",
"alien-инопланетянин",
"dynamic-динамический",
"scary-страшно",
"equation-уравнение",
"angel-ангел",
"offering-предложение",
"rage-гнев",
"photography-фотография",
"toilet-туалет",
"disappointed-разочарованный (от disappoint)",
"precious-драгоценный",
"prohibit-запрещать",
"realistic-реалистический",
"hidden-скрытый",
"tender-нежный t-",
"gathering-собрание",
"outstanding-выдающийся *u-",
"stumble-спотыкаться",
"lonely-одинокий",
"automobile-автомобиль",
"artificial-искусственный",
"dawn-рассвет",
"abstract-отвлеченный",
"descend-спускаться",
"silly-глупый",
"tide-прилив и отлив",
"shared-общий",
"hopefully-с надеждой !NEW!",
"readily-охотно r-",
"cooperate-сотрудничать",
"revolutionary-революционный",
"romance-романтика",
"hardware-аппаратные средства",
"pillow-подушка",
"kit-ранец",
"continent-континент",
"seal-печать",
"circuit-кругооборот",
"ruling-правящий (-ing)",
"shortage-нехватка",
"annually-ежегодно",
"lately-за последнее время",
"scan-Просмотр ",
"fool-дурак",
"deadline-крайний срок",
"rear-задняя часть",
"processing-обработка",
"ranch-ранчо",
"coastal-береговой",
"undertake-предпринимать",
"softly-мягко",
"burning-сжигание",
"verbal-словесный",
"tribal-племенной",
"ridiculous-нелепый",
"automatic-автоматический",
"diamond-алмаз",
"credibility-правдоподобие",
"import-импорт",
"sexually-сексуально",
"way-дорога",
"divine-божественный",
"sentiment-настроение",
"cart-телега",
"oversee-надзирать",
"elder-старший",
"pro-профессионал",
"inspiration-вдохновение",
"Dutch-Голландский",
"quantity-количество",
"trailer-прицеп к автомобилю",
"mate-товарищ",
"o'clock-час",
"Greek-греческий",
"genius-гений",
"monument-памятник (не memorial)",
"bid-Предложение ",
"quest-поиски",
"sacrifice-жертва",
"invitation-приглашение",
"accuracy-точность",
"juror-присяжный",
"officially-официально",
"broker-маклер",
"treasure-сокровище",
"loyalty-верность",
"talented-талантливый",
"gasoline-газолин",
"stiff-негнущийся",
"output-выпуск",
"nominee-номинальный",
"extended-растянутый",
"diabetes-диабет",
"slap-хлопать",
"toxic-токсичный",
"alleged-мнимый",
"jaw-челюсть",
"grief-горе",
"mysterious-таинственный",
"rocket-ракета",
"donate-жертвовать",
"inmate-обитатель",
"tackle-хватать *a-",
"dynamics-динамика",
"bow-кланяться",
"ours-наш",
"dignity-достоинство",
"carpet-ковер",
"parental-родительский",
"bubble-пузырь",
"buddy-дружище",
"barn-амбар",
"sword-меч",
"seventh-седьмой",
"glory-слава",
"tightly-плотно",
"protective-защитный",
"tuck-складка",
"drum-барабан",
"faint-слабый",
"queen-Королева",
"dilemma-дилемма",
"input-Вход ",
"specialize-специализировать",
"northeast-к северо",
"shallow-мелкий",
"liability-ответственность",
"sail-парус",
"merchant-торговец (не salesman)",
"stadium-стадион",
"improved-улучшил (от improve)",
"bloody-кровавый",
"associated-связанный",
"withdrawal-вывод",
"refrigerator-холодильник",
"nest-гнездо",
"thoroughly-тщательно",
"lane-дорожка (не road)",
"ancestor-предок",
"condemn-осуждать",
"steam-пар",
"accent-подчеркивать",
"optimistic-оптимистичный",
"unite-соединять(ся)",
"cage-клетка",
"equip-оборудовать",
"shrimp-креветка",
"homeland-Родина",
"rack-полка для багажа над сиденьем",
"costume-костюм",
"hay-сено",
"courtroom-зал суда",
"statute-закон",
"cartoon-мультфильм",
"productivity-производительность",
"grin-ухмыляться",
"symbolic-символический",
"bug-клоп",
"bless-благословлять",
"aunt-тетя",
"agriculture-сельское хозяйство",
"hostile-враждебный (не adverse)",
"conceive-постигать",
"combined-Объединенный ",
"instantly-немедленно",
"bankruptcy-банкротство",
"vaccine-вакцина",
"bonus-премия",
"collaboration-сотрудничество",
"mixed-смешанный",
"opposed-Противопоставленный ",
"orbit-орбита",
"grasp-понять",
"patience-терпение",
"spite-злость",
"tropical-тропический",
"voting-голосование",
"patrol-патруль",
"willingness-готовность",
"revelation-откровение",
"calm-успокаивать",
"jewelry-Ювелирные изделия",
"Cuban-кубинский",
"haul-тянуть (не pull)",
"concede-уступать",
"wagon-повозка !NEW!",
"afterward-Позже ",
"spectacular-производящий глубокое впечатление; впечатляющий; эффектный",
"ruin-гибель",
"sheer-настоящий",
"immune-иммунный",
"reliability-надежность",
"ass-осел (библ.)",
"alongside-рядом",
"bush-куст",
"exotic-экзотический",
"fascinating-очаровательный",
"clip-стричь",
"thigh-бедренная кость",
"bull-бык",
"drawer-чертежник",
"sheep-овца",
"discourage-обескураживать",
"coordinator-координатор",
"ideological-идеологический",
"runner-бегун",
"secular-светский",
"intimate-глубокий",
"empire-империя",
"cab-наемный экипаж",
"exam-экзамен",
"documentary-документальный",
"neutral-нейтральный",
"biology-биология",
"flexible-гибкий",
"progressive-прогрессирующий",
"web-ткань",
"conspiracy-заговор",
"casualty-несчастный случай",
"republic-республика",
"execution-выполнение",
"terrific-потрясающий",
"whale-кит",
"functional-функциональная",
"instinct-инстинкт",
"teammate-товарищ по команде",
"aluminum-алюминий",
"whoever-кто бы ни",
"ministry-министерство",
"verdict-вердикт",
"instruct-инструктировать",
"skull-череп",
"cooperative-кооперативный",
"manipulate-манипулировать",
"bee-пчела",
"practitioner-практикующий врач",
"loop-петля",
"edit-редактировать",
"whip-кнут",
"puzzle-приводить в затруднение",
"mushroom-гриб",
"subsidy-субсидия",
"boil-кипятить",
"tragic-трагический",
"mathematics-математика",
"mechanic-механик",
"jar-ссора",
"earthquake-землетрясение",
"pork-свинина",
"creativity-креативность",
"safely-безопасно",
"underlying-лежащий в основе",
"dessert-десерт",
"sympathy-симпатия",
"fisherman-рыбак",
"incredibly-невероятно",
"isolation-изоляция",
"sock-носок",
"eleven-одиннадцать",
"sexy-сексуальный",
"entrepreneur-предприниматель",
"syndrome-синдром",
"bureau-бюро",
"workplace-рабочее место",
"ambition-честолюбие",
"touchdown-посадка",
"utilize-использовать",
"breeze-легкий ветер",
"costly-дорогостоящий",
"ambitious-честолюбивый",
"Christianity-христианство",
"presumably-возможно",
"influential-влиятельный",
"translation-перевод",
"uncertain-неясный (не от слова clear)",
"dissolve-растворять",
"statistical-статистический",
"gut-потрошить",
"metropolitan-столичный",
"rolling-прокатка",
"aesthetic-эстетический",
"spell-писать или произносить (слово) по буквам",
"insert-вставлять",
"booth-кабинка",
"helmet-шлем",
"waist-талия",
"expected-предполагаемый",
"lion-лев",
"accomplishment-достижение",
"royal-королевский (не queen)",
"panic-паника",
"crush-раздавить",
"actively-активно",
"cliff-утес",
"minimal-минимальный",
"cord-шнур",
"fortunately-к счастью",
"cocaine-кокаин",
"illusion-иллюзия",
"anonymous-анонимный",
"tolerate-терпеть",
"appreciation-признательность",
"commissioner-уполномоченный",
"flexibility-гибкость",
"instructional-учебный",
"scramble-карабкаться",
"casino-казино",
"tumor-опухоль",
"decorate-украшать",
"pulse-пульс",
"equivalent-эквивалент",
"fixed-назначил (от fix)",
"experienced-опытный",
"donation-денежное пожертвование",
"diary-дневник",
"sibling-родной брат",
"irony-Ирония",
"spoon-ложка",
"midst-середина",
"alley-аллея",
"interact-взаимодействовать",
"soap-мыло",
"cute-изящный",
"rival-соперник",
"punch-пробивать (отверстия)",
"pin-булавка",
"hockey-хоккей",
"passing-прохождение",
"persist-упорствовать",
"supplier-поставщик",
"known-известен",
"momentum-импульс",
"purse-кошелек",
"shed-сарай",
"liquid-жидкость",
"icon-значок",
"elephant-слон",
"consequently-следовательно",
"legislature-законодательная власть",
"franchise-франшиза",
"correctly-правильно",
"mentally-умственно",
"foster-воспитывать",
"bicycle-велосипед",
"encouraging-обнадеживающий",
"cheat-обманывать",
"heal-излечивать",
"fever-жар",
"filter-фильтр; фильтровать",
"rabbit-кролик",
"coin-монета",
"exploit-эксплуатировать",
"accessible-доступный",
"organism-организм",
"sensation-чувство s-",
"partially-Частично ",
"upstairs-наверху",
"dried-сушеный",
"conservation-сохранение",
"shove-толкать(ся)",
"backyard-задний двор",
"charter-чартер",
"stove-печь",
"consent-разрешение",
"comprise-включать",
"reminder-напоминание",
"alike-похожий",
"placement-размещение",
"dough-тесто d-",
"grandchild-внук",
"dam-дамба",
"reportedly-по сообщениям",
"surrounding-Окружение ",
"ecological-экологический",
"outfit-снаряжение",
"unprecedented-беспрецедентный",
"columnist-обозреватель",
"workout-разрабатывать",
"preliminary-предварительный (p- не preparatory)",
"patent-патент",
"shy-застенчивый",
"trash-мусор",
"disabled-искалеченный",
"gross-большой (не large)",
"damn-черт",
"hormone-гормон",
"texture-текстура",
"pencil-карандаш",
"frontier-граница *r-",
"spray-брызги",
"disclose-раскрывать",
"custody-опека",
"banker-банкир",
"beast-зверь",
"interfere-мешать",
"oak-дуб",
"eighth-восьмой",
"notebook-тетрадь (n-)",
"outline-контур",
"attendance-присутствие",
"speculation-размышление",
"uncover-раскрывать",
"behalf-Защита ",
"innovative-инновационный",
"shark-акула",
"mill-фабрика",
"installation-Установка ",
"stimulate-стимулировать",
"tag-бирка",
"vertical-вертикальный",
"swimming-плавание",
"fleet-флот",
"catalog-каталог",
"outsider-аутсайдер",
"desperately-отчаянно !NEW!",
"stance-позиция",
"compel-принуждать",
"sensitivity-чувствительность",
"someday-когда",
"instant-мгновение",
"debut-дебют",
"proclaim-провозглашать",
"worldwide-Мировой",
"hike-путешествовать пешком",
"required-потребованный (не demanded) !NEW!",
"confrontation-конфронтация",
"colorful-красочный c-",
"constitution-конституция",
"trainer-тренер",
"Thanksgiving-благодарение",
"scent-запах",
"stack-стог",
"eyebrow-бровь",
"sack-мешок",
"cease-прекращать",
"inherit-(у)наследовать",
"tray-поднос",
"pioneer-пионер",
"organizational-организационной",
"textbook-учебник",
"uh-эм",
"nasty-скверный",
"shrink-отпрянуть",
"emerging-появление",
"dot-точка",
"wheat-пшеница",
"fierce-свирепый",
"envision-воображать",
"rational-рациональный",
"kingdom-королевство",
"aisle-придел",
"weaken-ослабевать",
"protocol-Протокол ",
"exclusively-исключительно ***l-",
"vocal-вокальный",
"marketplace-рыночная площадь",
"openly-открыто",
"unfair-несправедливый",
"terrain-местность",
"deploy-развертывать",
"risky-рискованный",
"pasta-макаронные изделия",
"genre-жанр",
"distract-отвлекать",
"merit-достоинство",
"planner-планировщик",
"depressed-подавленный",
"chunk-ломоть",
"closest-ближайший",
"discount-скидка",
"ladder-лестница (не stairs)",
"jungle-джунгли",
"migration-миграция",
"breathing-дыхание",
"invade-вторгаться",
"hurricane-ураган h-",
"retailer-розничный торговец",
"classify-классифицировать",
"coup-переворот",
"ambassador-посол",
"density-плотность",
"supportive-поддержка",
"curiosity-любопытство",
"skip-пропускать (часто бывает при устано !NEW!",
"aggression-агрессия",
"stimulus-стимул",
"journalism-журналистика",
"robot-Робот ",
"dip-погружать",
"likewise-так же !NEW!",
"informal-неофициальный",
"Persian-персидский",
"feather-предмет гордости",
"sphere-сфера",
"tighten-сжимать (не squeeze)",
"boast-хвастовство",
"pat-хлопок",
"perceived-Воспринятый ",
"sole-подошва",
"publicity-гласность",
"unfold-раскрываться",
"validity-период действия",
"ecosystem-экосистема",
"strictly-строго *t-",
"partial-частичный",
"collar-воротник",
"weed-сорняк",
"compliance-соблюдение",
"streak-полоса",
"supposedly-предположительно",
"added-добавленной",
"builder-строитель",
"glimpse-мелькание",
"premise-предпосылка",
"specialty-специальность",
"deem-считать",
"artifact-артефакт",
"sneak-ябеда",
"monkey-обезьяна",
"mentor-наставник",
"two-два",
"listener-слушатель",
"lightning-молния",
"legally-законно",
"sleeve-рукав",
"disappointment-разочарование",
"disturb-нарушать",
"rib-ребро (не hip)",
"excessive-чрезмерное",
"debris-обломки",
"rod-прут",
"logical-логический",
"ash-ясень",
"socially-социально",
"parish-приход",
"slavery-рабство",
"blank-пустой",
"commodity-товар",
"cure-лекарство",
"mineral-минeральный",
"hunger-голод (h-)",
"dying-погибающий",
"developmental-развивающий",
"faster-быстрее",
"spare-уделять",
"halfway-на полпути !NEW!",
"equality-равенство",
"cemetery-кладбище",
"harassment-беспокойство",
"deliberately-сознательно",
"fame-слава",
"regret-жалеть",
"striking-бьющий",
"likelihood-вероятность",
"carrot-морковь",
"atop-сверху",
"toll-Потери",
"rim-ободок",
"embarrassed-смущенный",
"fucking-чертов",
"cling-цепляться",
"isolated-изолированный",
"blink-мерцание",
"suspicious-подозрительный",
"wheelchair-инвалидная коляска",
"squad-команда",
"eligible-подходящий (не suitable)",
"processor-процессор",
"plunge-нырять p-",
"this-этот",
"demographic-демографический",
"chill-холод",
"refuge-убежище",
"steer-править (рулём)",
"legislator-законодатель",
"rally-ралли",
"programming-программирование",
"cheer-настроение",
"outlet-выход",
"intact-неповрежденный",
"vendor-продавец",
"thrive-преуспевать; буйно",
"peanut-земляной орех",
"chew-жевать",
"elaborate-тщательно разработанный",
"conception-концепция",
"auction-аукцион",
"steak-бифштекс",
"comply-уступать",
"triumph-триумф",
"shareholder-акционер",
"comparable-сравнимый",
"transport-транспорт",
"conscience-совесть",
"calculation-расчет",
"considerably-значительно (не tremendously)",
"interval-антракт",
"scratch-царапать",
"awake-бодрствующий",
"jurisdiction-юрисдикция",
"inevitably-неизбежно",
"feminist-феминистка",
"constraint-Ограничение ",
"emotionally-эмоционально",
"expedition-экспедиция",
"allegedly-якобы",
"similarity-сходство",
"butt-приклад",
"lid-крышка",
"dumb-немой",
"bulk-груз",
"sprinkle-кропить",
"mortality-смертность",
"philosophical-философский",
"conversion-превращение",
"patron-покровитель",
"municipal-муниципальный",
"liver-печень",
"harmony-гармония",
"solely-Исключительно ",
"tolerance-толерантность",
"goat-козел",
"blessing-благословение -ing",
"banana-банан",
"palace-дворец",
"formerly-прежде",
"peasant-крестьянский",
"neat-чистый",
"grandparent-бабушка или дедушка",
"lawmaker-законодатель",
"supermarket-супермаркет",
"cruise-морское путешествие (c-)",
"mobile-подвижный",
"calendar-календарь",
"widow-вдова",
"deposit-взнос",
"beard-борода",
"brake-тормоз",
"screening-скрининг",
"impulse-побуждение",
"forbid-запрещать",
"fur-мех",
"brutal-грубый",
"predator-хищник",
"poke-толчок",
"opt-выбирать",
"voluntary-добровольный",
"valid-правильный v-",
"forum-Форум",
"dancing-танцы -ing",
"happily-счастливо",
"soar-витать",
"removal-перемещение r-",
"autonomy-автономия",
"enact-предписывать",
"thread-нитка",
"landmark-ориентир",
"unhappy-несчастный",
"offender-правонарушитель",
"coming-приход",
"privately-конфиденциально",
"fraction-дробь",
"distinctive-отличительный",
"tourism-туризм",
"threshold-порог",
"routinely-обычно",
"suite-номер люкс",
"regulator-регулятор",
"straw-пустяк",
"theological-теологический",
"exhaust-исчерпывать",
"globe-земной шар",
"fragile-хрупкий",
"objection-возражение",
"chemistry-химия",
"crowded-многолюдный",
"blast-взрыв",
"prevail-торжествовать (не triumph)",
"overnight-с ночевкой",
"denial-отрицание",
"rental-аренда",
"fantastic-фантастический",
"fragment-отрывок",
"screw-привинчивать",
"warmth-тепло",
"undergraduate-студент",
"headache-головная боль",
"policeman-полицейский",
"projection-проекция",
"suitable-подходящий",
"graduation-градация",
"drill-дрель",
"cruel-жестокий",
"mansion-дворец",
"grape-виноград",
"authorize-санкционировать",
"cottage-коттедж",
"driveway-проезд !NEW!",
"charm-очарование",
"sexuality-сексуальность",
"loyal-верный",
"clay-глина",
"balloon-воздушный шар",
"invention-выдумка",
"ego-эго",
"fare-плата за проезд",
"homework-домашнее задание",
"disc-диск",
"sofa-диван",
"availability-доступность",
"radar-радиолокационный",
"frown-нахмуриться",
"regain-достичь",
"sweater-эксплуататор",
"rehabilitation-реабилитация",
"rubber-резина",
"retreat-отступать",
"molecule-молекула",
"freely-свободно",
"favorable-благоприятный",
"steadily-неуклонно",
"integrated-интегрированный",
"ha-ха",
"youngster-юноша",
"premium-премия",
"accountability-подотчетность",
"overwhelm-засыпать",
"contemplate-созерцать",
"update-Модернизация ",
"spark-искра",
"ironically-иронически",
"fatigue-усталость",
"speculate-спекулировать",
"marker-маркер",
"preach-проповедовать",
"bucket-ведро",
"blond-белокурый",
"confession-признание",
"provoke-вызывать",
"marble-мрамор",
"substantially-по существу",
"defender-защитник",
"explicit-ясный  e-",
"disturbing-тревожный",
"surveillance-наблюдение",
"magnetic-магнитные",
"technician-специалист t-",
"mutter-бормотать",
"devastating-разрушительный",
"depart-отбывать",
"arrow-стрела",
"trauma-травма",
"neighboring-близлежащий",
"soak-впитывать",
"ribbon-лента",
"meantime-между тем",
"transmit-передавать",
"harvest-урожай",
"consecutive-последовательный",
"republican-республиканец",
"coordinate-координировать",
"spy-шпион",
"slot-слот",
"riot-бунт",
"nutrient-питательный",
"citizenship-гражданство",
"severely-строго (*e-)",
"sovereignty-суверенитет",
"ridge-горный хребет",
"brave-храбрый",
"lighting-освещение",
"specify-точно определять",
"contributor-сотрудник",
"frustrate-срывать",
"articulate-артикулировать",
"importantly-важно",
"transit-транзит",
"dense-густой",
"seminar-семинар",
"electronics-электроника",
"sunny-солнечный",
"shorts-трусики",
"swell-отличный",
"accusation-обвинение",
"soften-смягчать(ся)",
"straighten-выпрямлять(ся)",
"terribly-ужасно t-",
"cue-кий",
"bride-невеста",
"biography-биография",
"hazard-шанс",
"compelling-неотразимый",
"seldom-редко",
"tile-черепица",
"economically-экономически",
"honestly-честно !NEW!",
"troubled-побеспокоил (от trouble)",
"twentieth-двадцатый",
"balanced-уравновешенный",
"foreigner-иностранец",
"convenience-удобство",
"delight-восхищение",
"weave-ткать",
"timber-бревно",
"till-до",
"accurately-точно",
"plea-мольба",
"bulb-луковица",
"flying-летающий",
"sustainable-устойчивый",
"devil-дьявол",
"bolt-молния",
"cargo-груз",
"spine-позвоночный столб",
"seller-торговец (не trader)",
"skilled-квалифицированный",
"managing-управление",
"marine-морской флот",
"dock-док",
"organized-организовывал (от organize)",
"fog-туман",
"diplomat-дипломат",
"boring-скучный",
"sometime-когда",
"summary-конспект",
"missionary-миссионер",
"epidemic-эпидемический",
"fatal-фатальный",
"trim-подрезка",
"warehouse-склад",
"accelerate-ускорять",
"butterfly-бабочка",
"bronze-бронзовый",
"drown-тонуть",
"inherent-неотъемлемый",
"nationwide-общенациональный",
"spit-плеваться",
"kneel-становиться на колени",
"vacuum-вакуум",
"selected-Отобранный ",
"dictate-диктовать",
"stereotype-стереотип",
"sensor-датчик",
"laundry-прачечная",
"manual-ручной",
"pistol-револьвер",
"naval-флотский",
"plaintiff-истец",
"apology-извинение",
]
